### ISSUE TITLE
`nagivation_and_routing`: back button doesn't return to the previous page

### ISSUE THREAD

**Issue by asashour** [flutter/samples#1003]
**Steps**:

1. Use Chrome as web application
2. Sign in
3. Click on `All` books
4. Click on a book
5. Click on the Back button of the Application, not of the Browser.
![image](https://user-images.githubusercontent.com/2410127/151945801-663f92e9-fa22-475d-89a1-4ca2e93b138f.png)

**Expected**:

The application goes to `All`

**Actual**:

The application goes to `Popular`

**Comment by akshaykh10** [comment]
Hey can I take up the issue?

**Comment by saikumarkusangi** [comment]
Hello @asashour can i start my first contribution from this issue ?

**Comment by domesticmouse** [comment]
You don't need permission to attempt a fix. It might help to verify that this is still an issue first, however.

**Comment by domesticmouse** [comment]
@johnpryan is the work you are doing in this space going to change the status of this issue?

**Comment by sasanktumpati** [comment]
I'm unable to replicate this issue.
I think we could clode it or am I missing anything?
@domesticmouse 
https://github.com/flutter/samples/assets/76063158/fff2a3f8-c397-410c-99ef-f59aca5be22c

**Comment by domesticmouse** [comment]
Thanks for the replication attempt @sasanktumpati
