### ISSUE TITLE
flutter2.8.1 FlutterEngineGroup Exception:Failed to access the internal image decoder registry on this isolate 

### ISSUE THREAD

**Issue by chrisLiuYan** [flutter/samples#1008]
https://github.com/flutter/flutter/issues/98013#issue-1126893485

**Comment by domesticmouse** [comment]
Which sample is this related to?

**Comment by chrisLiuYan** [comment]
multiple_flutters_ios
I changed your sample and found this problem
[multiple_flutters_module_ios.zip](https://github.com/flutter/samples/files/8038514/multiple_flutters_module_ios.zip)

**Comment by domesticmouse** [comment]
Looks like the linked issue has been closed as resolved.
