### ISSUE TITLE
How to run platform_design?

### ISSUE THREAD

**Issue by BernhardSchlegel** [flutter/samples#1027]
Hi there, 

flutter newbie here. I'm simply trying to launch the "platform_design" sample app. I'm getting an insane amount of errors. What did I do wrong?

Steps to reproduce:
1. Cloning "flutter/samples" 
2. Opening "samples" as root folder in VSCode (also tried opening "./samples/platform_design" as root)
3. selecting "./samples/platform_design/lib/main.dart"
4. hitting run.

My other playground app that I've build from scratch runs fine. Dependencies listed in pubspec.yaml were installed.

Thanks for your patience and guidance in advance,
Bernhard.

**Comment by srihamat** [comment]
@BernhardSchlegel Please check and share the error at the VSCode's output screen, 

My guess is if you are using old version of SDK then you will see the message "platform_design requires SDK version >=2.17.0-0 <3.0.0

**Comment by domesticmouse** [comment]
Closing out as stale
