### ISSUE TITLE
Add sample app (state management & request use one package) 

### ISSUE THREAD

**Issue by M97Chahboun** [flutter/samples#1050]
I want add this [example](https://github.com/JahezAcademy/mc/tree/main/example) app build by ([mc package](https://pub.dev/packages/mc) for state management & request )
[mc package explanation](https://github.com/JahezAcademy/mc/blob/staging/mc_package.jpg) 
Thank you.

**Comment by domesticmouse** [comment]
Looks like `mc` has been discontinued.

**Comment by M97Chahboun** [comment]
@domesticmouse yes, now I split it 
with new name [flutter_rocket](https://pub.dev/packages/flutter_rocket)

I will open new PR with new example
