### ISSUE TITLE
Use of prefixes

### ISSUE THREAD

**Issue by michalmytych** [flutter/samples#1080]
Should one letter [prefixes actually be used in Flutter code? ](https://dart.dev/guides/language/effective-dart/style#dont-use-prefix-letters)

https://github.com/flutter/samples/blob/c6bee7aa930b83c2032d06d3802d0f840dd3d558/navigation_and_routing/lib/main.dart#L34

**Comment by domesticmouse** [comment]
This one comes from the Flutter API: https://api.flutter.dev/flutter/foundation/kIsWeb-constant.html
