### ISSUE TITLE
gh-pages workflow is broken

### ISSUE THREAD

**Issue by craiglabenz** [flutter/samples#1270]
During I/O, deploying updated builds of the `gh-pages` branch (which powers https://flutter.github.io/samples/#) hit quite a few snags. These need to be thoroughly explored and fixed.

**Comment by parlough** [comment]
This looks to have been fixed with https://github.com/flutter/samples/commit/9b840e61c84ba097e4d07974dcaae45827241c5c resulting in https://github.com/flutter/samples/commit/a118790bcd52526d731a7f0c4559689045bf44e6
