### ISSUE TITLE
`material_3_demo` Small fixes

### ISSUE THREAD

**Issue by guidezpl** [flutter/samples#1276]
Collecting feedback from myself and designers in a single place:

- [ ] When Material 2 is on, should swap out `NavigationBar` for `BottomNavigationBar`
- [ ] When Material 2 is on, selected color for navigation rail is clashing
  <img width="65" alt="Screen Shot 2022-05-19 at 17 58 21" src="https://user-images.githubusercontent.com/6655696/169345060-a0e90d1e-c87c-4d4b-abfc-2df408d7c763.png">
- [x] The layout for the components page on large screens could be improved b/233040660
- [x] Cards could be shown to be larger so that they are recognisable as cards
- [ ] Preset colors could be replaced with color picker. While presets are nice, `MaterialSwatch` colors are to be deprecated and we want to encourage exploration in the RGB space

cc @QuncCccccc

**Comment by domesticmouse** [comment]
It feels like this issue is under specified 😎

**Comment by guidezpl** [comment]
take that back! :)

**Comment by ericwindmill** [comment]
Closing as Material 3 is the default
