### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by fiorins** [flutter/samples#1284]
Hi, I install the app but it doesn't show the "favorites" & "visited" markers on the map but only "want to go" places, however they are shown only in the list view, i wondering if i am the only one to have this kind of error, thanks
<img width="383" alt="Immagine 2022-05-26 130124" src="https://user-images.githubusercontent.com/32281481/170475789-8c9a307a-1630-4e58-8fe9-3fa13e58bb9f.png">
<img width="380" alt="Immagine 2022-05-26 130152" src="https://user-images.githubusercontent.com/32281481/170475792-8a78d4ec-a3bb-4cd4-9f64-e1890f34b581.png">
<img width="383" alt="Immagine 2022-05-26 130215" src="https://user-images.githubusercontent.com/32281481/170475796-6bd8b97c-17af-4dd6-80ff-e3792ce2c9c7.png">
<img width="382" alt="Immagine 2022-05-26 130237" src="https://user-images.githubusercontent.com/32281481/170475797-8fbfd8cc-6bf7-4f82-81c4-2040eec0ae3a.png">

**Comment by fiorins** [comment]
I didn't import the files in asset folder ;)

**Comment by domesticmouse** [comment]
> I didn't import the files in asset folder ;)

Oh I've done that, more than once 🤪
