### ISSUE TITLE
game_template has navigation error

### ISSUE THREAD

**Issue by craiglabenz** [flutter/samples#1288]
After pressing the AppBar's Back button from the level screen, the following logs appear:

```sh
SEVERE: 2022-05-28 10:54:16.715: GoRouter: Exception during GoRouter navigation
SEVERE: 2022-05-28 10:54:16.715: GoRouter: Exception during GoRouter navigation
```

And the screen looks like this:

<img width="1200" alt="Screen Shot 2022-05-28 at 11 00 00 AM" src="https://user-images.githubusercontent.com/855034/170830952-f46d53f6-d9de-425e-9315-23a5248a5b94.png">

**Comment by glsee** [comment]
In my case, the AppBar is already disabled and hidden from view in the template. I'm unable to trigger the error.

![image](https://user-images.githubusercontent.com/457429/175762008-71738a43-03d0-464c-b162-67db7a3a5eaa.png)

**Comment by ChristianEdwardPadilla** [comment]
I can repro this on web (doesn't repro on mobile).

Steps:

1. Navigate to a level and win.
2. Wait for confetti animation to end and press "continue".
3. Try to navigate back.
4. Observe error.

On mobile, step 3 leads back to the initial app screen.

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Just confirming I'm on this. Thanks for your patience!
