### ISSUE TITLE
[add-to-app] Android multiple flutter cells within recycler view

### ISSUE THREAD

**Issue by reytum** [flutter/samples#1299]
Hi All,
 
The sample for add-to-app android shows how to add a FlutterView to Android recycler view. But the sample only adds a flutter cell once the previous one has been recycled. Is there a way to add multiple flutter cells in Android recycler view? Here's the link to the sample: https://github.com/flutter/samples/blob/main/add_to_app/android_view/android_view/app/src/main/java/dev/flutter/example/androidView/ListAdapter.kt

**Comment by domesticmouse** [comment]
Hey @gaaclarke, do we have samples for multiple Flutters?

**Comment by gaaclarke** [comment]
> Hey @gaaclarke, do we have samples for multiple Flutters?

https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters is this what you are looking for?

**Comment by reytum** [comment]
@gaaclarke @domesticmouse Thanks. Was able to use multiple engines and reuse them based on the visible views in the recycler view. This fulfils my use case.
