### ISSUE TITLE
Crash: flutter plugin module crash while trying to reopen terminated app.

### ISSUE THREAD

**Issue by abhayam17** [flutter/samples#1323]
Flutter plugin module is crashing when re-open ios main application that has been killed/terminated either by manually from background or killed when change the camera permission from settings.
Similar way flutter fullscreen integrated iOS app is not working when re-open the terminated or killed app.

Please find the relevant crash video in following link given below
https://drive.google.com/file/d/1EQS6FO1flUtQswRsp5C3FvUaIgbOfQEL/view?usp=sharing

Specifications: 
iOS version: 15+
device: iPad/iPhone

**Comment by domesticmouse** [comment]
The linked file seems to be a PNG. No idea what is going on here.

Can you please raise an issue against the flutter/flutter issue tracker with a reproduction case?
