### ISSUE TITLE
Add license headers to Material 3 demo

### ISSUE THREAD

**Issue by danny-laa** [flutter/samples#1327]
The [top level LICENSE file](https://github.com/flutter/samples/blob/main/LICENSE) contains three different licenses,

- 3-clause BSD License
- SIL Open Font License
- Apache License

Which one applied to the code in this repo? Is this repo dual licensed under BSD and Apache?

**Comment by domesticmouse** [comment]
See individual files for which license each file is under.

**Comment by danny-laa** [comment]
But not every file has a license header in it.

For example, I found no license header within [the material_3_demo folder](https://github.com/flutter/samples/blob/main/material_3_demo/)

**Comment by danny-laa** [comment]
@domesticmouse But not every file has a license header in it.

For example, I found no license header within [the material_3_demo folder](https://github.com/flutter/samples/blob/main/material_3_demo/)

**Comment by domesticmouse** [comment]
That’d be a bug
