### ISSUE TITLE
I am using the Game Template but during run there is some error occurs

### ISSUE THREAD

**Issue by moshOntong-IT** [flutter/samples#1363]
I encountered some minor problem when I am starting to run my flutter game project using the Game template.
"Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01"
<img width="835" alt="image" src="https://user-images.githubusercontent.com/57244338/182896294-cf559bbf-1c73-472c-9aae-7446535f84c9.png">

Although, it build and run successfully.

**Comment by domesticmouse** [comment]
What are the reproduction steps for this issue? 

/cc @filiph

**Comment by moshOntong-IT** [comment]
I didnt change the game template I just run it and I show this minor error on debug log.
