### ISSUE TITLE
Add the website to the GitHub "About" section

### ISSUE THREAD

**Issue by justinmc** [flutter/samples#1373]
Would it make sense to add the link to the website (https://flutter.github.io/samples/) to the About section @domesticmouse?  Usually I look for links like that there and was surprised to not see it.  There should be a gear icon in the About section of the main repo page that reveals a "website" field.

![Screenshot from 2022-08-09 12-57-07](https://user-images.githubusercontent.com/389558/183749556-82b2c68d-300b-482a-981c-90c114106617.png)

**Comment by domesticmouse** [comment]
I think this makes sense. @johnpryan, WDYT?

**Comment by johnpryan** [comment]
SGTM

**Comment by johnpryan** [comment]
We could also consider creating subdomain like samples.flutter.dev

**Comment by johnpryan** [comment]
Un-assigning myself since I can't edit the sidebar.

@Hixie could you add a link to "https://flutter.github.io/samples/" to the sidebar here?

**Comment by Hixie** [comment]
I checked "Use your GitHub Pages website".

**Comment by johnpryan** [comment]
Looks great, thanks!

**Comment by justinmc** [comment]
Thanks everyone! :tada:
