### ISSUE TITLE
The splashscreen sample does not work

### ISSUE THREAD

**Issue by ronw98** [flutter/samples#1394]
Tested on android emulator API 32
![image](https://user-images.githubusercontent.com/44091831/187021572-2a769612-8954-4465-b6a8-8e9dc8857677.png)

Flutter doctor:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/44091831/187021603-68db2384-46c2-46e8-b273-28b1592901a5.png">

**Comment by domesticmouse** [comment]
Hey @camsim99, do you have a time to poke the `android_splash_screen` sample to figure out how it broke?

**Comment by ronw98** [comment]
Actually this might be a bug on the emulator or android studio, the splash screen doesn't show when run using android studio but launching the app normally on the simulator shows the splashscreen as expected
