### ISSUE TITLE
Simplistic Editor: unexpected behavior of TextInputClient on web

### ISSUE THREAD

**Issue by LucasAschenbach** [flutter/samples#1413]
When using the [simplistic_editor](https://github.com/flutter/samples/tree/main/simplistic_editor), the TextEditingValue seems to fork into two different states after delete operations while skipping characters during deletion.

# Steps to Reproduce
1. Open https://flutter.github.io/samples/web/simplistic_editor/#/ (or build for web)
2. Clear text field
3. Type `afafaf`
4. Perform 6 delete operations (During deletion, the text value will alternate between two states. The last value is `aaf` while an empty text value would be expected)
5. Upon pressing the right arrow key, the input will change to `fff`

Notice how there are unsolicited NonTextUpdate operations added, whenever a character is skipped.

On mobile (iOS) and desktop (macOS) the demo works as expected.

---
**Browser:** Chrome 104.0.5112.101 (Official Build) (arm64)

**Comment by domesticmouse** [comment]
PTAL @Renzo-Olivares

**Comment by Renzo-Olivares** [comment]
Thanks will check this out!
