### ISSUE TITLE
Add this Shortcut / Intent / Action sample?

### ISSUE THREAD

**Issue by justinmc** [flutter/samples#1419]
This issue is mainly directed at @domesticmouse, who brought this up to me when I was rehearsing my Flutter Vikings talk.

GitHub repo: https://github.com/justinmc/flutter_shortcut_intent_action_talk
Live demo: https://justinmc.github.io/flutter_shortcut_intent_action_talk/#/

I made an app to go along with a talk on Shortcuts, Intents, and Actions, and I'm wondering if it is something that we should include in this samples repo.  In its current state, the app is a bit too tightly tied to the talk, and the code is a bit messy, but if I fix that, then would this sample be welcome here?

I think the best approach might be to remove all demos and questions and just pare it down to the drawing app, unless someone thinks that there's a way to make those useful here.

Let me know and I'm happy to open a PR!

**Comment by domesticmouse** [comment]
I'm supportive of this sample being included. Thoughts @craiglabenz and @johnpryan?

**Comment by domesticmouse** [comment]
@justinmc Closing out this issue. Please feel free to create PRs for new content when required.
