### ISSUE TITLE
SimplisticEditor: Strange behavior which text changing on click

### ISSUE THREAD

**Issue by cgestes** [flutter/samples#1450]
extracted from https://github.com/flutter/samples/issues/1424#issuecomment-1260520780

backspace doesn't work correctly on the web, in the example deleting multiples chars in a row with backspace make the text alternates between two differents values.

deleting "brown", I get:
```The quick rw fox jumps over the lazy dog.```

if I click anywhere on the text it alternates with:
```The quick bo fox jumps over the lazy dog.```

If I select some text, the alternation stops.

**Comment by domesticmouse** [comment]
PTAL @Renzo-Olivares
