### ISSUE TITLE
Don't understand how to make FlutterView transparent and control z-index both at same the time.

### ISSUE THREAD

**Issue by himanshu634** [flutter/samples#1459]
Currently, I am learning to integrate flutter into native android and understanding FlutterView.
I have come to the point where I want transparency and also want to control the z-index of the FlutterView. But If I pass the `FlutterSurfaceView(this, true)` class in the constructor then I can get transparency but it will bring FlutterView to the top of all android layers. And when I use `FlutterTextureView(this)` in the constructor of FlutterView then I can make a flutter view between other android views but I can not control the transparency of the FlutterView. So I don't know how to control transparency and z-index both at the same time.

**Comment by domesticmouse** [comment]
Per our [Community](https://flutter.dev/community) page, I'd suggest either asking on our Discord, Community Slack, or StackOverflow. This issue tracker is for recording issues with the samples. Thanks!
