### ISSUE TITLE
the logo doesn't appear till the second launch of the app

### ISSUE THREAD

**Issue by ayoubXOXO** [flutter/samples#1471]
i am working with flutter version 3.3.4.
i have been struggling to make the splash screen on android 12 and above to work , and finally i found out that it works but only when you restart the app from hot restart and not cold restart ,
honestly i started to think to move to react native...
3 days no sleep because of a splash screen that's quite too much

**Comment by domesticmouse** [comment]
Which sample are you reporting an issue with? I'm confused 🫤

**Comment by ayoubXOXO** [comment]
> Which sample are you reporting an issue with? I'm confused 🫤

the sample
[(https://github.com/flutter/samples/tree/main/android_splash_screen)]

steps that results the issue :

1-configure splash screen with a logo in center of the screen for android 11 and below and android 12 and above
2-run the app on android 11 and below ==> everything works as expected splash screen background  changed logo added
3-run the app on android 12 and above ==>splash screen background changed logo doesn't appear

NOTE : Logo does appear after you relaunch the app manually from the emulator and not running from the IDE

**Comment by domesticmouse** [comment]
@camsim99 any idea what is going wrong here?

**Comment by camsim99** [comment]
@ayoubXOXO What IDE are you using? I want to try to reproduce the issue so I can rule out this being caused by your environment.

**Comment by domesticmouse** [comment]
Closing this out as stale.
