### ISSUE TITLE
Roll new changes into `package:mdc_web` then update in samples_index

### ISSUE THREAD

**Issue by parlough** [flutter/samples#1472]
We currently have to [override](https://github.com/flutter/samples/blob/main/web/samples_index/pubspec.yaml#L26-L31) the `sass` dependency due to a previous issue with Material Components Web which the fix for has not yet rolled into `package:mdc_web`. Due to changes in modern `sass` versions, we also have to restrict `sass_builder` to an old version.

We should incorporate the new changes into `package:mdc_web`, then update the packages here and remove the necessary overrides.

**Comment by ericwindmill** [comment]
Closing, as the samples index is being deprecated
