### ISSUE TITLE
Document how to add window_size as a dependency 

### ISSUE THREAD

**Issue by rida2025** [flutter/samples#1475]
[first_app] flutter pub add window_size
Because first_app depends on window_size any which doesn't exist (could not find package window_size at https://pub.dartlang.org), version solving failed.
pub finished with exit code 65
exit code 65

**Comment by domesticmouse** [comment]
`window_size` isn't published on pub.dev. If you look at the `pubspec.yaml` files in this repo you will see that the `window_size` dependency is actually on a Git repository. See https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages for guidance on how to add these packages to your app.
