### ISSUE TITLE
Extra page shown when swiping back in Safari on iOS

### ISSUE THREAD

**Issue by MarcBritton** [flutter/samples#1478]
Tested using the `Navigation and Routing` application from the Flutter samples.
https://github.com/flutter/samples/tree/main/navigation_and_routing
I built this application for the web (`flutter build web`), then ran a local webserver on MacOS in build/web and connected to it with Safari from my iPhone.

When you swipe from outside the left edge of the screen across to the right on a Flutter Web app running in Safari on an iOS device, an 'extra' page is shown in the slide transition animation that shouldn't be there.

The bug only occurs if you begin your swipe from *outside* the left edge of the display and then swipe across. If you begin from slightly inside the left edge of the screen, only 2 screens are displayed in the transition and it looks correct.

I tested this swiping behaviour in other web pages/apps and it doesn't occur, so it seems to be specific to Flutter.

I also tested in the Chrome browser from my iOS device and the same problem occurs, so it seems the problem is not specific to Safari.

The video shows alternating swipes first from the outside the left edge, then inside.

https://user-images.githubusercontent.com/7886473/196312434-f7795a98-5c35-45ec-bfb1-4f2c51c472b9.mov

**Comment by domesticmouse** [comment]
It'd be useful to boil this down to a minimal reproduction case and then file against the flutter/flutter repo.

**Comment by johnpryan** [comment]
This is likely fixed in https://github.com/flutter/samples/pull/1437

**Comment by MarcBritton** [comment]
Sorry, I meant to file this issue again the flutter/flutter repo. This appears to be a problem in a flutter itself, nothing to do with a specific Flutter sample.

I have opened a new issue here: https://github.com/flutter/flutter/issues/114324
