### ISSUE TITLE
Game Toolkit is breaking CI with Flutter 3.3.7

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#1494]
Broken CI run: https://github.com/flutter/samples/actions/runs/3383386242/jobs/5619229358#step:5:1

In similar cases I’ve bumped Firebase dependencies to fix the issue.

**Comment by filiph** [comment]
So weird that this broke with a simple `pub upgrade`. Semver! :shakes fist at clouds: Looking into it.
