### ISSUE TITLE
[samples][add_to_app] No such module 'FlutterModuleRegistrant'

### ISSUE THREAD

**Issue by keciman** [flutter/samples#1500]
I did all the steps as described here: https://github.com/flutter/samples/tree/main/add_to_app/multiple_flutters/multiple_flutters_ios

During the build of the app I get error `No such module 'FlutterModuleRegistrant'`
My Xcode is up to date version 14.0 as well as my macOS.
Flutter version I have is 3.3.8. 

Maybe the repo is outdated ? Or am I doing something Wrong ?

<img width="1139" alt="Screenshot 2022-11-16 at 15 15 11" src="https://user-images.githubusercontent.com/29520217/202203844-62094ae2-1278-4db2-b213-ea27bb2fbd33.png">

**Comment by domesticmouse** [comment]
Hey @gaaclarke, any ideas?

**Comment by gaaclarke** [comment]
The `FlutterModuleRegistrant` is the module that provides the `GeneratedPluginRegistrant.register` down below.  There is some magic that I don't know off the top of my head that generates that code from what plugins are installed in the flutter project.  That one in particular may be a Swift bridge to that generated objc code, adding more magic on magic.  

Things to check:
1) Make sure you have open `./multiple_flutters_ios/MultipleFluttersIos.xcworkspace`, not `./multiple_flutters_ios/MultipleFluttersIos.xcodeproj` (probably your issue)
1) run `flutter pub get` in `./multiple_flutters_module`

**Comment by keciman** [comment]
@gaaclarke I did all the steps as stated in the example app which are the same as the steps you stated here above. I tried even once more for us to be sure. It did not help.

You gave me and idea that there could be problem with bridging file. I experienced issue with that sometimes. In the Xcode settings there is no bridging header set. I will try to go through and make it work then reply here.

**Comment by keciman** [comment]
@gaaclarke Ok my assumption up there was quite non sense. The issue is probably somewhere else. The solution for me was to just comment out the line with `import FlutterModuleRegistrant` and the line with 
`GeneratedPluginRegistrant.register(with: newEngine)` not really proud of that but other solution might take me too much time and this just builded app and it worked. Thanks for your time. Last time I tried it it did not work but now somehow it did which is great.

**Comment by keciman** [comment]
Altough the app works without the lines above. It is not connected with native iOS. The MethodChannel methods can not be found even tho they are implemented.

**Comment by gaaclarke** [comment]
I just downloaded and ran the example fine.  Your repo may be goofed.  Try this (where // is the path to the repo and origin is your remote):

```
cd //
git clean -df
git fetch origin
git checkout origin/main
cd //add_to_app/multiple_flutters/multiple_flutters_module
flutter pub get
cd //add_to_app/multiple_flutters/multiple_flutters_ios
pod install
open MultipleFluttersIos.xcworkspace
```

Then build and run from xcode.

I've seen no evidence that there is anything wrong with the sample beyond the fact there is a couple of pitfalls that make running the sample harder than it should be.

**Comment by keciman** [comment]
Thanks so much it helped me. I will close this issue.
