### ISSUE TITLE
Building/Running sample 'desktop_photo_search' project reports error 

### ISSUE THREAD

**Issue by snoop911** [flutter/samples#1505]
flutter doctor says 'No Issues Found', yet trying to run the sample project it shows:

Unsplash Access Key is required. Please add to `lib/unsplash_access_key.dart`.

I think I have everything installed so not sure what this means.

**Comment by domesticmouse** [comment]
From the `README` files:

This desktop application enables you to search [Unsplash](https://unsplash.com/) for photographs that interest you. 
To use it, you need to add an **Access Key** from [Unsplash API](https://unsplash.com/developers) to `lib/unsplash_access_key.dart`.
