### ISSUE TITLE
Please help, I have a problem with BottomNavigationBar

### ISSUE THREAD

**Issue by HydraBabakri** [flutter/samples#1507]
When I connect the application to the phone, I run it, and this appears

It also appears in the DEBUG CONSOLE list, which is in blue and does not stop counting

`Exception has occurred. _AssertionError ('package:flutter/src/material/bottom_navigation_bar.dart': Failed assertion: line 188 pos 11: 'items.every((BottomNavigationBarItem item) => item.label != null)': Every item must have a non-null label)`

**Comment by domesticmouse** [comment]
This isn't the forum for debugging random code. Per https://flutter.dev/community I'd strongly suggest posting this question on https://stackoverflow.com/tags/flutter

To make it possibly for people to be able to help you debug your issue, I strongly suggest creating a minimal reproduction of the issue and post it at GitHub so people can review your code. See https://stackoverflow.com/help/minimal-reproducible-example for more detail.
