### ISSUE TITLE
[M3] Group components by taxonomy group 

### ISSUE THREAD

**Issue by guidezpl** [flutter/samples#1510]
We should use the taxonomy groups listed at https://m3.material.io/components to group the components page on the m3 sample app. cc @QuncCccccc

**Comment by domesticmouse** [comment]
@guidezpl I'm assigning this issue to you and @QuncCccccc, but feel free to push back if there should be a different owner for this issue.

**Comment by QuncCccccc** [comment]
Thanks for letting me know. Will reorganize them:)

**Comment by guidezpl** [comment]
Totally down to contribute. I haven't been able to figure out where the latest code is. Using the `master`/`main` branch, I get the stable layout. Which branch is the [latest work](https://flutter-experimental-m3-demo.web.app/#/) on?

**Comment by domesticmouse** [comment]
It's not on a branch, it's in the `experimental` directory.
