### ISSUE TITLE
game_template navigation error

### ISSUE THREAD

**Issue by peengle** [flutter/samples#1514]
When `GoRouter.of(context).pop()` method is used on router to get back to previous screen it breaks navigation flow. 

https://github.com/flutter/samples/blob/56fa9f93e3d723f00e4b1c54f2be68859d7407f0/game_template/lib/src/settings/settings_screen.dart#L106

Steps to reproduce:

- Run Flutter Game Template app
- Goto Settings screen [Settings]
- Go back to Home screen [Back]
- Once again try to go to Settings screen [Settings] (this time nothing will happen) 

Consider to use `GoRouter.of(context).go('/')` instead `pop()` or use `push(...)` instead of `go(...)` method to jump to new screen.

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Hi @peengle, thanks for the report!

I couldn't reproduce this at first, but then it occurred to me to upgrade dependencies (with `go_router` still pinned at major version 5 with `^5.0.5`). After upgrading, navigation indeed broke.

This is quite frustrating. I'm guessing the new behavior was always the intended behavior, and `game_template` worked correctly until now _despite_ me holding it wrong. I should have double checked that `pop()` indeed does what I thought it did (remove a level of navigation, i.e. go to the previous `/`).

Anyway, I'm fixing it now. PR coming soon. Thanks again for the report.
