### ISSUE TITLE
Add samples for Flutter ffi projects

### ISSUE THREAD

**Issue by jmagman** [flutter/samples#1547]
Add samples for every FFI scenario listed on the website
iOS: https://docs.flutter.dev/development/platform-integration/ios/c-interop.  Note these should be validly submittable to the App Store (validate with TestFlight).
macOS: https://docs.flutter.dev/development/platform-integration/macos/c-interop also validate with TestFlight
Android: https://docs.flutter.dev/development/platform-integration/android/c-interop

**Comment by domesticmouse** [comment]
Would a sample that integrates [Duktape](https://duktape.org/) to generate a JS REPL on Android, iOS, Windows, Linux and macOS be sufficient?

**Comment by jmagman** [comment]
I don't have a preference for what functionality is added, I want working examples for these platforms based on our setup instructions.  I also don't care if it's a codelab or sample in this repo, as long as it's linked from the website documentation.

**Comment by domesticmouse** [comment]
FYI @leighajarett

**Comment by wajahat414** [comment]
also please add a reference or guide for static library examples for the ios platform  using ffi plugin,

**Comment by domesticmouse** [comment]
Closing this out as I have created [Using FFI in a Flutter plugin](https://codelabs.developers.google.com/codelabs/flutter-ffigen) showing how to use Duktape on Android, iOS, Linux, Windows, and macOS.
