### ISSUE TITLE
provider_shopper: login screen enter button not having visible text

### ISSUE THREAD

**Issue by ChronoTrax** [flutter/samples#1559]
The login screen enter button of provider_shopper has yellow text on a yellow button, making the text not visible.

**Comment by johnpryan** [comment]
Thanks for filing an issue, we might want to make sure we're not [setting the wrong attribute](https://github.com/flutter/samples/blob/main/provider_shopper/lib/screens/login.dart#L42) on the buttons - this could be a breaking change from Material 3 but I'm not sure.

**Comment by domesticmouse** [comment]
PTAL @miquelbeltran

**Comment by miquelbeltran** [comment]
This sample is still using Material 2. I'll address this issue when I migrate it to Material 3.

**Comment by miquelbeltran** [comment]
Issue closed in https://github.com/flutter/samples/pull/1560/files
