### ISSUE TITLE
pedometer: Fails to run (missing files?)

### ISSUE THREAD

**Issue by justinmc** [flutter/samples#1595]
I'm unable to run the experimental/pedometer app on a local emulator (iOS or Android).  Is it missing some files that should be checked in?

```
Expected ios/Runner.xcodeproj but this file is missing.
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.
```

```
AndroidManifest.xml could not be found.
Please check /Users/jmccandless/Projects/samples/experimental/pedometer/android/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_arm64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.
```

**Comment by domesticmouse** [comment]
PTAL @leighajarett

**Comment by domesticmouse** [comment]
PTAL @HosseinYousefi

**Comment by HosseinYousefi** [comment]
Pedometer itself is a plugin. The app is inside pedometer/example. Are you running the correct project?

I'm asking because of the path in the logs.

**Comment by justinmc** [comment]
Fail, that was my problem.  Thanks.  Here's a PR in case I'm not the only one who missed that: https://github.com/flutter/samples/pull/1928
