### ISSUE TITLE
`experimental/material_3_demo` is broken

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#1642]
<img width="912" alt="Screenshot 2023-02-08 at 4 49 43 pm" src="https://user-images.githubusercontent.com/30503/217446106-25b5e5ea-3017-4330-8f93-3ffcbda74474.png">

Can you please:
 - Add some tests
 - Unbreak the sample
 - Not sign off code that isn't tested

Thanks!

**Comment by guidezpl** [comment]
I'm not sure why you merged this... I was looking for feedback and didn't have a chance to respond to the review.
