### ISSUE TITLE
[simplistic_editor] IME candidate panel place wrong

### ISSUE THREAD

**Issue by pedia** [flutter/samples#1648]
## Steps to Reproduce

In the sample [simplistic_editor](https://flutter.github.io/samples/web/simplistic_editor/), IME selection panel place is wrong.

**Expected results:** 
The panel should be under the carer as below
<img width="572" alt="image" src="https://user-images.githubusercontent.com/170561/217830600-430998c1-9135-48a0-93d6-a8037554839b.png">

**Actual results:** 
<img width="687" alt="image" src="https://user-images.githubusercontent.com/170561/217829446-b029238a-144c-4c07-81ea-bf68084ef067.png">

This error is on macos, windows and web.

Thanks.

**Comment by pedia** [comment]
@domesticmouse Any ideas?

**Comment by pedia** [comment]
On macOS too.

The ime  engine is `Pinyin`, but also reproduced with `Japanese`.

**Comment by domesticmouse** [comment]
Quick question, are you seeing this behaviour with only this sample? Or is it replicating with normal multi line text areas as well?

**Comment by pedia** [comment]
This behaviour is only in the sample.

**Comment by domesticmouse** [comment]
PTAL @Renzo-Olivares

**Comment by Renzo-Olivares** [comment]
This is on my radar. Thanks for the heads up @domesticmouse

**Comment by pedia** [comment]
@Renzo-Olivares How about the progress of this issue?
All open sourced RichEdit failed. Maybe I should turn to HTML tech instead of flutter.
