### ISSUE TITLE
Is it possible to trigger native android function from flutter side after starting flutter activity 

### ISSUE THREAD

**Issue by anonghostteamz** [flutter/samples#1667]
Is it possible to trigger native android function from flutter side after starting flutter activity. I add flutter as module in native android now I want to call function from flutter module to native android but nothing works, I have tried MethodChannel and Pigeon. but both says that "Not able to establish connection". 
Please give some way to do so, I know its not a project issue but we really need this process, and project only shows native android to flutter function triggering not vice versa

**Comment by godwinpinto** [comment]
Check this out: https://protocoderspoint.com/how-to-call-native-android-code-from-flutter/

**Comment by domesticmouse** [comment]
https://stackoverflow.com/questions/tagged/flutter is a better place to ask questions like this. Thanks!
