### ISSUE TITLE
[Simplistic_Editor] Keys do not appear to work on MacOs

### ISSUE THREAD

**Issue by n-doton** [flutter/samples#1679]
When running the simplistic editor sample on MacOs, the backspace, delete, insert and arrow keys do not appear to work. Is any further configuration required to use this sample on desktop?

**Comment by domesticmouse** [comment]
PTAL @Renzo-Olivares

**Comment by Renzo-Olivares** [comment]
Hi @n-doton thanks for reporting this. Those keys should not require additional configuration. Looks like that was probably due to this change in the framework https://github.com/flutter/flutter/pull/115900, working on a quick PR to fix this.

**Comment by n-doton** [comment]
@Renzo-Olivares Thanks for the quick response! Much appreciated
