### ISSUE TITLE
Scrolling Material 3 demo's second column causes stuttering

### ISSUE THREAD

**Issue by HansMuller** [flutter/samples#1680]
In debug mode on MacOS, slowly scrolling the second column of the Material 3 demo's component screen causes significant stuttering:

https://user-images.githubusercontent.com/1377460/221660738-d85bb65a-a0d8-435d-8b93-9bf1d5a62d2f.mov

**Comment by HansMuller** [comment]
CC @QuncCccccc @Piinks

**Comment by Piinks** [comment]
@HansMuller are you dragging on the scrollbar in the video? Or scrolling with a mouse?

**Comment by Piinks** [comment]
Filed https://github.com/flutter/flutter/issues/121574 to follow up

**Comment by HansMuller** [comment]
Dragging the scrollbar thumb.

**Comment by Piinks** [comment]
Fixed with https://github.com/flutter/flutter/pull/121786
The scrollbar will still move around as the content is loaded, but it will not cause the actual content to move around as well.
For more context on this fix, see: https://github.com/flutter/flutter/pull/121786#discussion_r1129803106

**Comment by QuncCccccc** [comment]
> Fixed with [flutter/flutter#121786](https://github.com/flutter/flutter/pull/121786) The scrollbar will still move around as the content is loaded, but it will not cause the actual content to move around as well. For more context on this fix, see: [flutter/flutter#121786 (comment)](https://github.com/flutter/flutter/pull/121786#discussion_r1129803106)

Thanks so much! Just deployed the latest web version for the experimental demo: https://flutter-experimental-m3-demo.web.app/#/
