### ISSUE TITLE
Use `BrowserContextMenu` in the context menu sample

### ISSUE THREAD

**Issue by navaronbracke** [flutter/samples#1685]
The `context_menu` sample at https://github.com/flutter/samples/tree/main/experimental/context_menus
still states that the samples do not work on web.

However, there is now a new API that enables using the `contextMenuBuilder` on the web, namely `BrowserContextMenu`.
We should update the samples to use that API and remove the note at the top of the sample.

We also had to update the examples in the SDK itself [here](https://github.com/flutter/flutter/issues/119184).

Side note: The context menu API's are not experimental anymore, since they are now available on stable.

**Comment by domesticmouse** [comment]
Hey @justinmc, I'm sticking this on your TODO list =)

**Comment by justinmc** [comment]
Thanks for pointing this out, on it!
