### ISSUE TITLE
[simplistic_text_editor] - up/down arrows throw an error on MacOs

### ISSUE THREAD

**Issue by n-doton** [flutter/samples#1693]
When trying to navigate the text area on MacOs using the up/down arrows, the following error is thrown:

`Unable to find an action for an Intent with type ExtendSelectionVerticallyToAdjacentLineIntent in an
Actions widget in the given context.
Actions.invoke() was unable to find an Actions widget that contained a mapping for the given intent,
or the intent type isn't the same as the type argument to invoke (which is Intent - try supplying a
type argument to invoke if one was not given)
The context used was:
  Focus(focusNode: FocusNode#65713([PRIMARY FOCUS]), dependencies: [_ActionsMarker, _FocusMarker],
state: _FocusState#f953b)
The intent type requested was:
  ExtendSelectionVerticallyToAdjacentLineIntent`

**Comment by domesticmouse** [comment]
Can you please supply the output of `flutter doctor -v`?

**Comment by n-doton** [comment]
@domesticmouse Here you go:

[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
    • Flutter version 3.7.5 on channel stable at /Users/user/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c07f788888 (13 days ago), 2023-02-22 17:52:33 -0600
    • Engine revision 0f359063c4
    • Dart version 2.19.2
    • DevTools version 2.20.1

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/user/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/user/Desktop/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.75.1)
    • VS Code at /Users/user/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177

[✓] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by domesticmouse** [comment]
Steps to replicate:
  - `flutter run -d macos`
  - fill text area with enough content to have multiple lines
  - press up arrow

```console
$ flutter run
Multiple devices found:
macOS (desktop) • macos  • darwin-arm64   • macOS 13.3 22E5236f
darwin-arm64
Chrome (web)    • chrome • web-javascript • Google Chrome 111.0.5563.64
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Running "flutter pub get" in simplistic_editor...
Resolving dependencies... 
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  js 0.6.5 (0.6.7 available)
  matcher 0.12.13 (0.12.14 available)
  meta 1.8.0 (1.9.0 available)
  path 1.8.2 (1.8.3 available)
  test_api 0.4.16 (0.4.18 available)
Got dependencies!
Launching lib/main.dart on macOS in debug mode...
Updating minimum macOS deployment target to 10.14.
Upgrading project.pbxproj
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Removing script build phase dependency analysis.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001250C00C38801E }
{ platform:macOS, arch:x86_64, id:00006000-001250C00C38801E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...                                           
Syncing files to device macOS...                                    45ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at:
http://127.0.0.1:53664/6zSez2R5zDk=/
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:53664/6zSez2R5zDk=/

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY
╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.performSelectors:
Unable to find an action for an Intent with type
ExtendSelectionVerticallyToAdjacentLineIntent in an
Actions widget in the given context.
Actions.invoke() was unable to find an Actions widget that contained a mapping for the given
intent,
or the intent type isn't the same as the type argument to invoke (which is Intent - try
supplying a
type argument to invoke if one was not given)
The context used was:
  Focus(focusNode: FocusNode#ed3e7([PRIMARY FOCUS]), dependencies: [_ActionsMarker,
  _FocusMarker],
state: _FocusState#71d38)
The intent type requested was:
  ExtendSelectionVerticallyToAdjacentLineIntent

When the exception was thrown, this was the stack:
#0      Actions.invoke.<anonymous closure> (package:flutter/src/widgets/actions.dart:885:9)
#1      Actions.invoke (package:flutter/src/widgets/actions.dart:899:6)
#2      BasicTextInputClientState.performSelector
(package:simplistic_editor/basic_text_input_client.dart:119:17)
#3      ListMixin.forEach (dart:collection/list.dart:86:13)
#4      TextInput._handleTextInputInvocation
(package:flutter/src/services/text_input.dart:1874:19)
#5      TextInput._loudlyHandleTextInputInvocation
(package:flutter/src/services/text_input.dart:1753:20)
#6      MethodChannel._handleAsMethodCall
(package:flutter/src/services/platform_channel.dart:555:55)
#7      MethodChannel.setMethodCallHandler.<anonymous closure>
(package:flutter/src/services/platform_channel.dart:548:34)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
(package:flutter/src/services/binding.dart:393:35)
#9      _invoke2 (dart:ui/hooks.dart:183:13)
#10     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#11     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#12     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#13     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#14     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)

call:
  MethodCall(TextInputClient.performSelectors, [1, [moveUp:]])
═════════════════════════════════════════════════════════════════════════════════════════════
═══════
```

**Comment by domesticmouse** [comment]
PTAL @Renzo-Olivares

**Comment by Renzo-Olivares** [comment]
These shortcuts were not originally implemented in this demo, but I think since now it is inheriting the shortcut mapping from `DefaultTextEditingShortcuts` instead of a local `Shortcuts` widget this error is popping up. I'll try to add another mapping for the currently unsupported shortcuts so it stops erroring.

**Comment by n-doton** [comment]
Hi @Renzo-Olivares,

Have there been any updates on this?
