### ISSUE TITLE
`material_3_demo` shows black system navigation bar.

### ISSUE THREAD

**Issue by TahaTesser** [flutter/samples#1720]
| material_3_demo| Native |
| --------------- | --------------- |
|  <img src="https://user-images.githubusercontent.com/48603081/229297088-b785ce76-14f6-4262-9b07-4afff67b6bc6.png" height="450" /> |  <img src="https://user-images.githubusercontent.com/48603081/229297170-bfc35af8-2d8d-4b63-bbc0-f01b7a3e19c6.jpg" height="450" /> |

**Comment by domesticmouse** [comment]
PTAL @QuncCccccc
