### ISSUE TITLE
`experimental/context_menus` where's paste?

### ISSUE THREAD

**Issue by sgehrman** [flutter/samples#1721]
I set up BrowserContextMenu.disableContextMenu and it works, but I only see copy, cut, select all.  Where's paste?

I'm on flutter web canvaskit (beta channel) latest.

**Comment by sgehrman** [comment]
I figured it out, but why isn't this on by default??  The xerox parc did this but flutter doesn't think it's standard?

**Comment by domesticmouse** [comment]
PTAL @justinmc

**Comment by justinmc** [comment]
What did you figure out?  I actually didn't intend for paste to be turned off on web.

**Comment by domesticmouse** [comment]
Closing out as stale
