### ISSUE TITLE
in app purchase not working

### ISSUE THREAD

**Issue by alixumer** [flutter/samples#1734]
SettingsScreen ->

When tap on

_SettingsLine(
'Remove ads',
icon,
onSelected: callback,
);

**Comment by domesticmouse** [comment]
Is this to do with the in app purchases codelab? Or a specific sample?

**Comment by alixumer** [comment]
it belongs to the game template

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
Hi @alixumer, can you tell me what the error looks like, if any? Did you have any trouble while setting the in-app purchases as described in https://github.com/flutter/samples/tree/main/game_template#in-app-purchases ?

**Comment by domesticmouse** [comment]
Closing out as stale. Please comment to re-open.
