### ISSUE TITLE
Gradle exception in `add_to_app` sample

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#1800]
The [tests for the beta branch](https://github.com/flutter/samples/actions/runs/4929755000/jobs/8809793595) are failing due to this Gradle error:

```
== Testing 'add_to_app/fullscreen/android_fullscreen' on Flutter's stable channel ==
~/work/samples/samples/add_to_app/fullscreen/android_fullscreen ~/work/samples/samples

Welcome to Gradle 8.1.1!

Here are the highlights of this release:
 - Stable configuration cache
 - Experimental Kotlin DSL assignment syntax
 - Building with Java 20

For more details see https://docs.gradle.org/8.1.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Script '/opt/hostedtoolcache/flutter/beta-3.10.0-1.5.pre-x64/packages/flutter_tools/gradle/module_plugin_loader.gradle' line: 59

* What went wrong:
A problem occurred configuring root project 'AndroidFullScreen'.
> A problem occurred configuring project ':flutter'.
   > Failed to notify project evaluation listener.
      > org/gradle/api/plugins/MavenPlugin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 1m 43s
Error: Process completed with exit code 1.
```

**Comment by domesticmouse** [comment]
I'll be honest, assigning this to me will just get the sample deleted. I don't know enough Android to debug this situation. Probably best to find an engineer who knows Android well enough to get it fixed.

**Comment by parlough** [comment]
@reidbaker Would you be able to help us out here?

**Comment by reidbaker** [comment]
I think this is related to https://github.com/flutter/flutter/issues/126403

Where do yall define the version of gradle/AGP we have not fixed all the deprecrations related to agp 8.0 and have not tested gradle 8.1.

**Comment by domesticmouse** [comment]
I've had a go at updating the gradle files, but it's failing in a way I don't understand. I'm not an Android dev ;-)

PR: https://github.com/flutter/samples/pull/1862
Failure: https://github.com/flutter/samples/actions/runs/5152005544/jobs/9277713367?pr=1862

**Comment by domesticmouse** [comment]
@miquelbeltran fixed this one

**Comment by parlough** [comment]
Our hero!

**Comment by RK9260** [comment]
* What went wrong:
Could not determine the dependencies of task ':flutter_plugin_android_lifecycle:test'.
> Could not create task ':flutter_plugin_android_lifecycle:testReleaseUnitTest'.
   > this and base files have different roots: D:\Omnidya\GITHUB\omnidya-client-app\build\flutter_plugin_android_lifecycle and C:\Users\RAJ\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_plugin_android_lifecycle-2.0.17\android.    for flutter 3.19.6 with java 11 can any one help
