### ISSUE TITLE
Reduce dependabot pull requests for web_embedding/ng-flutter sample

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#1809]
This sample is an angular app, and after https://github.com/flutter/samples/pull/1774, we're getting too many pull requests

For example, when Angular 16.0.1 was released, we got these pull requests:

- https://github.com/flutter/samples/pull/1804  
- https://github.com/flutter/samples/pull/1805
- https://github.com/flutter/samples/pull/1806
- https://github.com/flutter/samples/pull/1807
- https://github.com/flutter/samples/pull/1808

We could change the interval to "weekly" and look for [other ways](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow) to reduce the number of PRs, such as `update-types: ["version-update:semver-minor"]` or setting `allow` to `dependency-type: "direct"`.

cc: @ditman @domesticmouse

**Comment by ditman** [comment]
We setup the "update-types" to ignore minor and patch versions in flutter/packages. I've sent a PR to mimic that configuration (and hopefully reduce the amount of PRs coming from npm dependabot!!)
