### ISSUE TITLE
Ng-flutter "package:web" mentioned

### ISSUE THREAD

**Issue by NashIlli** [flutter/samples#1819]
Hello! I'm reading the example of ng-flutter and I read that in the future there will be a package:web for JSInterop functions or something similar.
![image](https://github.com/flutter/samples/assets/6954280/21f20068-4293-4d3e-9971-bf368838a9f7)

https://github.com/flutter/samples/blob/main/web_embedding/ng-flutter/flutter/lib/src/js_interop/dom.dart

I have an angular app and I'm migrating to flutter, so that example is very useful and I'm trying to make it work with my Flutter elements and my Angular App. 

I would like to know if the package web will be available soon or if we should use the current packages to make it work

**Comment by johnpryan** [comment]
You can try the beta by adding `web: ^0.1.0-beta` to your pubspec.yaml
