### ISSUE TITLE
`game_template`: Problem with `in_app_purchase`

### ISSUE THREAD

**Issue by elzahaby** [flutter/samples#1841]
When using the in_app_purchase as implemented I face some issues on iOS:
- first ever purchase of the thing works without any problem.
- renewing the subscription doesn't work. Every Time I press subscribe after the subscription has expired resolves in the error that the previous purchases have not been completed.
- adding a "force" completion code doesn't help. it gives a unpredictable behavior that sometimes it works when pressing subscribe and sometimes it doesn't work
- I think the issue stems from the fact that restore purchases is run on launch of the app several times when the subscription has expired. It keeps trying to restore the pruchase endlessly

**Comment by domesticmouse** [comment]
Which sample is this issue for?

**Comment by domesticmouse** [comment]
Closing as stale. Please comment to re-open if this is still an issue
