### ISSUE TITLE
Veggieseasons isn't using a clean Cupertino-style transition among the tabs

### ISSUE THREAD

**Issue by kriswuollett** [flutter/samples#1849]
The cross-fade takes too long and the final frame is too large of a jump -- very visible to see a white title disappear against a dark background. It should have the look and feel as the built-in Clock app.

Here is what I'm seeing for the following version set:

- `Flutter (Channel stable, 3.10.2, on macOS 13.3.1 22E772610a darwin-x64, locale en-US)`
- `Xcode - develop for iOS and macOS (Xcode 14.3)`
- iPhone 12 mini w/ iOS 16.4.1 (a)`
- Running commit `4f01fbb9c172ee870146acecc45fae66c3b49675` in release mode on device

https://github.com/flutter/samples/assets/1834192/76226581-fb11-4a5a-800f-f1452e645787

![IMG_9255](https://github.com/flutter/samples/assets/1834192/f7e047d8-a260-491a-9f5a-65e3c96236c5)

**Comment by domesticmouse** [comment]
This sample hasn't been updated in a while. Please feel free to create a PR to fix this issue, thanks!

**Comment by domesticmouse** [comment]
Assigning this to @RedBrogdon while we figure out if this sample should be updated or retired.

**Comment by ericwindmill** [comment]
This sample is going to be retired. I'm closing this issue #1838
