### ISSUE TITLE
game_template: Does not respect silence

### ISSUE THREAD

**Issue by Stef-GMS** [flutter/samples#1896]
While the game_template has settings that will silence audio, the app should and does not respect when a device's sound is muted.  This happens with both iOS simulator and actual device.

To duplicate on iOS simulator or device:
1) Turn on mute button.
2) Run app.
3) Perform steps that make sound.

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by ericwindmill** [comment]
The game template is being deprecated in favor of flutter/games.
