### ISSUE TITLE
`material_3_demo` Add link to source code inside demos

### ISSUE THREAD

**Issue by guidezpl** [flutter/samples#1972]
It's not obvious where to find source code when you are linked to the demo itself, e.g. https://flutter.github.io/samples/web/material_3_demo/#/

**Comment by goyalyashpal** [comment]
https://github.com/flutter/samples/blob/main/material_3_demo/lib/main.dart

**Comment by guidezpl** [comment]
exactly

**Comment by ericwindmill** [comment]
VSI is being deprecated, and a select few samples will be hosted for demo purposes. #2507
