### ISSUE TITLE
Enabled Firebase, lots of Warnings and Unable to upload dSYM

### ISSUE THREAD

**Issue by cliffordh** [flutter/samples#1991]
I am using a recent version of the game_template and turned on Firebase. I went through the Firebase configuration without a hitch (have previously done this with other apps so I'm pretty sure that worked ok). I've got a clean "flutter doctor" report but a lot of deprecation warnings and a problem with Pod versioning.

└> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2)
[✓] VS Code (version 1.76.0)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!

/Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebaseCorePlugin.m:64:42: warning: 'trackingID' is deprecated [-Wdeprecated-declarations]
  pigeonOptions.trackingId = (id)options.trackingID ?: [NSNull null];
                                         ^
In module 'FirebaseCore' imported from /Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebasePlugin.h:10:
@property(nonatomic, copy, nullable) NSString *trackingID DEPRECATED_ATTRIBUTE;
                                                          ^
In module 'Darwin' imported from /Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebaseCorePlugin.h:4:
        #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                           ^
/Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebaseCorePlugin.m:66:47: warning: 'androidClientID' is deprecated [-Wdeprecated-declarations]
  pigeonOptions.androidClientId = (id)options.androidClientID ?: [NSNull null];
                                              ^
In module 'FirebaseCore' imported from /Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebasePlugin.h:10:
@property(nonatomic, copy, nullable) NSString *androidClientID DEPRECATED_ATTRIBUTE;
                                                               ^
In module 'Darwin' imported from /Users/ACME/.pub-cache/hosted/pub.dev/firebase_core-2.15.0/macos/Classes/FLTFirebaseCorePlugin.h:4:
        #define DEPRECATED_ATTRIBUTE        __attribute__((deprecated))
                                                           ^
4 warnings generated.
2023-08-18 15:00:21.710 upload-symbols[95675:10636241] Unable to get file attributes for dSYM file at path "/Users/ACME/Work/flutter_dev/FooBarApp_v3/build/macos/Build/Products/Debug/game_template.app.dSYM/Contents/Resources/DWARF"

Processing dSYMs...
Command PhaseScriptExecution failed with a nonzero exit code
/Users/ACME/Work/flutter_dev/FooBarApp_v3/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'nanopb' from project 'Pods')

**Comment by domesticmouse** [comment]
PTAL @filiph

**Comment by filiph** [comment]
FWIW, I'm also getting the deprecation warnings, with the latest firebase plugins ([`firebase_core 2.15.1`](https://pub.dev/packages/firebase_core)).

As for the dSYM package, I guess we need a new documentation. For now, please try this StackOverflow answer: 
https://stackoverflow.com/questions/72891223/what-should-i-do-to-change-the-macosx-deployment-target-when-build-flutter-macos (I actually like the [second-to-best answer](https://stackoverflow.com/a/72892797/1416886) better than the accepted one. But it does require that you get your hands dirty with Xcode.)

**Comment by ericwindmill** [comment]
This game_template is being deprecated in favor of the flutter/games repository.
