### ISSUE TITLE
`material_3_demo` scrolling has jitters on 3.7

### ISSUE THREAD

**Issue by iliyami** [flutter/samples#2009]
Hi, I've just checked the [flutter material 3 demo](https://flutter-experimental-m3-demo.web.app/#/)  web site with my phone on chrome, and found out that scrolling has lags.

What's the problem? Is this an issue with the flutter framework itself or it's just a performance issue because of bad coding?

**Comment by Kataglyphis** [comment]
The problem still persists. I can reproduce it right now.
Anyone found a workaround and want to share it ? ;)

**Comment by ericwindmill** [comment]
Closing as this is not a problem with flutter/samples. Please raise the issue in flutter/flutter

**Comment by iapicca** [comment]
@TahaTesser  could move the issue to flutter?
seems like a material 3 kinda thing
