### ISSUE TITLE
[State Restoration in iOS] State Restoration in iOS does not work in veggieseasons 

### ISSUE THREAD

**Issue by thanhdatvo** [flutter/samples#2022]
Hi, 
I run the veggieseasons in release mode
<img width="825" alt="Screenshot 2023-09-21 at 12 22 12 PM" src="https://github.com/flutter/samples/assets/36273288/9522f06d-2428-4721-8982-e988bb37c6b6">
Following the "To test state restoration on iOS:" in this website https://api.flutter.dev/flutter/services/RestorationManager-class.html

However, the state restoration does not happen.

What could be wrong?

Thank you,

**Comment by domesticmouse** [comment]
Could you please add a description of the steps to reproduce this on https://github.com/flutter/samples/issues/1838?

**Comment by domesticmouse** [comment]
Closing as duplicate
