### ISSUE TITLE
Remove `src` directory for apps

### ISSUE THREAD

**Issue by spydon** [flutter/samples#2045]
Since the `src` directory is for hiding code from being automatically externally exported, it should only be needed for libraries and not for apps.

From [here](https://dart.dev/tools/pub/package-layout#implementation-files):
> But much of a package’s code is internal implementation libraries that should only be imported and used by the package itself. Those go inside a subdirectory of lib called src.

I can fix this up, if there isn't any reason that I have overseen why those `src` directories exist that is.

**Comment by domesticmouse** [comment]
While not required for apps, it is a useful habit to always put implementation into a `src` directory. It causes no harm, and makes it much easier when factoring apart an app into an app + library to already be in the habit of hiding away implementation.

**Comment by spydon** [comment]
Alright, I can buy that, even though I think that the majority of people that are using Flutter never creates any packages and for them this just adds an extra unnecessary level of depth in the project structure that they don't know what it is for, since `src` isn't explained anywhere in the docs about apps.
On another note, maybe `flutter create -t package' should create a `src` directory inside of lib too?

**Comment by domesticmouse** [comment]
> On another note, maybe flutter create -t package should create a src directory inside of lib too?

Can you please raise a ticket for this on the `flutter/flutter` project issue tracker?

**Comment by spydon** [comment]
It seems like most of the community isn't creating `src` directories when they are creating an app, if anyone is interested I did a very small survey here:
https://twitter.com/spydon/status/1715772111724134589
