### ISSUE TITLE
github.io playback

### ISSUE THREAD

**Issue by jonnyhotchkiss** [flutter/samples#2095]
Hi! I just found your site whilst trying to understand how the github.io works, after reading it's made automagically for every commit, but unlike with flutter access 

https://github.com/flutter/samples/issues/new 

== 

https://flutter.github.io/samples/#

I can't seem to access something like 
https://github.com/kennethreitz/infinite-state-sample-pack/blob/master/Loops/Awaken_116/loop.wav
via https://infinite-state-sample-pack.github.io/

I wondered if the secret sauce is enabling the "github pages" feature on the repo, but that isn't present on working flutter...

so how does one make an .io "page" to access (play in browser) audio like .mp3 that's on github?!

Thanks!!

**Comment by domesticmouse** [comment]
Can you point me at an example of where something under https://flutter.github.io/samples/ is automatically playing a `.wav` file from github?

**Comment by jonnyhotchkiss** [comment]
am struggling to reproduce my steps, or even find a thing on flutter today that generates audio/noise, so ok to close and if I find anything related I can update. appears I'm mistaken! thanks for reply 👍
