### ISSUE TITLE
Remove experimental/material_3_demo

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#2154]
I think we should consider removing experimental/material_3_demo now that we have material_3_demo at the root level. 

If we would like to experiment with changes we can use a separate branch. This has a few advantages over a separate directory:
- Keeping things up to date. Right now there are some differences between the two samples that aren't related to the `main` channel.
- It's easier to track the differences between the two samples. (Right now if you want to compare them you have to copy-paste experimental/material_3_demo to overwrite the material_3_demo/ and then see what's changed) A separate branch would make it a lot easier.
- It's easier for contributors and code owners to keep track of where to make changes (I accidentally made changes to experimental/ and no one noticed, even the code owners)
- Testing - I was able to land a change that broke the tests because we are only testing top-level projects.

See discussion on this thread: https://github.com/flutter/samples/pull/2152

**Comment by johnpryan** [comment]
@HansMuller could you weigh in on this?

**Comment by HansMuller** [comment]
Removing experimental/material_3_demo, now that we've made M3 the default, sounds like the right thing to do.

**Comment by kevmoo** [comment]
Fixed in 6c10c75e2b0859c5fcaf401a4d97f03b91794a52 - #2153
