### ISSUE TITLE
Add Badge to show number of items in the cart under provider_shopper

### ISSUE THREAD

**Issue by pkitutu** [flutter/samples#2211]
Under the sample provider shopper, as one picks items from the catalog, there's no counter which shows the number of items added to the cart. This is an improvement where the number of items will be indicated next to the cart button in top right corner

**Comment by ericwindmill** [comment]
Given that the PR was closed, and that this is an enhancement, I'm closing this issue. Feel free to re-open and/or make a PR in the future.
