### ISSUE TITLE
[Feature Request] Update sample 'web-element-embedding' to new Js-interop Api

### ISSUE THREAD

**Issue by sensn** [flutter/samples#2221]
I am looking for a sample for the new Js-interop API in dart 3.3.
web-element-embedding seems to still use the old API.
It would be great to see an updated example.

**Comment by parlough** [comment]
Thanks for the issue!

https://github.com/flutter/samples/commit/37e149d8a65da73e8d25977bfe8d7f362b5f1eb3 migrated the embedding example and https://dart.dev/interop/js-interop has links to other resources related to the new JS-interop.

Let us know if you have any issues with the sample. Thanks again :D
