### ISSUE TITLE
navigation_and_routing: Incorrect Redirection and Button Behavior in Author Details Screen and Settings Page

### ISSUE THREAD

**Issue by sasanktumpati** [flutter/samples#2223]
When navigating through the author_details screen in our application, encountering redirection issues to /books/all instead of the expected /books/all/book/[index]. Similarly, buttons within the Settings page are also redirecting to /books/all erroneously. This behavior deviates from the intended functionality and requires immediate attention to ensure a seamless user experience.

**Steps to Reproduce:**

- Navigate to the author_details screen in the application.
- Attempt to open any book from the author_details screen.
- Observe redirection to /books/all instead of /books/all/book/[index].
- Proceed to the Settings page.
- Interact with the buttons within the Settings page.
- Notice redirection to /books/all instead of expected behavior.

**Expected Behavior:**

- When opening a book from the author_details screen, the application should redirect to /books/all/book/[index] corresponding to the selected book.
- Buttons within the Settings page should perform their designated actions without redirection to /books/all.

**Video:** 

https://github.com/flutter/samples/assets/76063158/30ec304b-e6dc-4653-b4fb-8de0e518d880

**Comment by ericwindmill** [comment]
I cannot reproduce this. If the problem persists, please re-open this issue.
