### ISSUE TITLE
App Store Connect Issues: ITMS-91053: Missing API declaration / Required Reasons API #2527

### ISSUE THREAD

**Issue by balajiks-dev** [flutter/samples#2224]
I have submitted my app to the App Store which was deployed to TestFlight through XCode Flutter, and I got the following warning / error email:

ITMS-91053: Missing API declaration - Your app’s code in the “Runner” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

I have tried to add these declaration in the PrivacyInfo.xcprivacy in Xcode. Here is the added declaration but still getting the same warnings from AppStore. 

Here is the reference used: https://github.com/FlutterFlow/flutterflow-issues/issues/2527#issuecomment-1997577905

And also tried every possible ways in that github issue.

**Comment by ericwindmill** [comment]
Closing this as it isn't an issue with this repo. If you need help, consider asking for advice on the #hackers-devrel channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).
