### ISSUE TITLE
material_3_demo  content.css  downloaded twice

### ISSUE THREAD

**Issue by chen56** [flutter/samples#2244]
https://flutter.github.io/samples/web/material_3_demo/
 
m3 web sample content.css is too large and downloaded twice, two file are basically same: 

<img width="1505" alt="image" src="https://github.com/flutter/samples/assets/2039742/589dabe0-0a8f-4ee0-81e7-6c999ca35931">

**Comment by parlough** [comment]
Thanks for opening the issue @chen56! I don't see any `content.css`,  `content.js`, or `page.js` files when accessing the site, nor do I believe we include these. What's the source/initiator of the `content.js` file? Perhaps it's being installed by an extension or some rogue service worker?

**Comment by chen56** [comment]
@parlough 
Microsoft Edge
Version 124.0.2478.51 (Official build) (x86_64)

**Comment by parlough** [comment]
Thanks for your browser details!

Could you try in an incognito tab with extensions disabled? I can't reproduce this nor can I find anywhere these files would be introduced.

**Comment by chen56** [comment]
you are right  , disable extensions , every thing is ok ,cool ,thanks, my problem!
