### ISSUE TITLE
Update `material _3_demo` for ColorScheme updates

### ISSUE THREAD

**Issue by Thanos-P** [flutter/samples#2289]
It looks like the *surfaceVariant* and *onSurfaceVariant* colors have been removed from the [demo](https://flutter.github.io/samples/web/material_3_demo/) colors. Furthermore, the *onBackground* has been erroneously replaced by *onSurface*.
![image](https://github.com/flutter/samples/assets/45496456/41baef54-29a4-4557-b0ef-8ade5a473e14)

**Comment by parlough** [comment]
Thanks for opening an issue! We just haven’t gotten around to updating the app for the latest `ColorScheme` changes.
