### ISSUE TITLE
 Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by tiagosilas** [flutter/samples#2332]
../../.pub-cache/hosted/pub.dev/flutter_markdown-0.6.9+1/lib/src/style_sheet.dart:302:34: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
      tableBody: theme.textTheme.bodyText2,
                                 ^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/tiago/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:

Flutter Version:
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (9 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by CraigFoote** [comment]
I'm still getting this. Any ideas?

**Comment by domesticmouse** [comment]
This was fixed in `flutter_markdown` 0.6.10+4. Bumping `flutter_markdown` dependencies to current released version.

**Comment by bihujrj** [comment]
flutter/packages/flutter/lib/src/material/text_theme.dart:105:10: Error: 'bodyText2' isn't an instance field of this class.
    this.bodyText2
         ^^^^^^^^^
Target kernel_snapshot_program failed: Exception

**Comment by domesticmouse** [comment]
> flutter/packages/flutter/lib/src/material/text_theme.dart:105:10: Error: 'bodyText2' isn't an instance field of this class. this.bodyText2 ^^^^^^^^^ Target kernel_snapshot_program failed: Exception

I'm curious what the repro steps for this are. This error is complaining about the Flutter source code itself, which seems... odd?
