### ISSUE TITLE
[simplistic_editor] How to I get a copy of text and display it in a separate widget

### ISSUE THREAD

**Issue by dkliss** [flutter/samples#2338]
Hi,

I have attempted to use the simplistic_editor and it works as expected. What I wanted to do was to be able to get the output of the formatted text and then convert that to json for example and then able to use another widget to display that formatted text. I looked at replacement controller but it only includes the text data and not the format information to be able to reprint this separately into a widget if I want to save and open the formatted file of  text. I was wondering if there is a way to save formatted text and then retrieve back later or if this is not implemented. Either way any guidance is appreciated. Thanks!

**Comment by ericwindmill** [comment]
On the [Community](flutter.dev/community) page on flutter.dev, you can find links to join the Discord or Community Slack. Both are great resources to get help with Flutter.

Because the sample works as expected, I'm closing this issue.
