### ISSUE TITLE
Update docs related to Flutter spash screen

### ISSUE THREAD

**Issue by ayyysh04z** [flutter/samples#2361]
Hey @camsim99,
can you mention the need of using main_activity.xml and main_activity2.xml used in sample project.
both screen aren't rendered once in the project.

repo : https://github.com/flutter/samples/tree/main/android_splash_screen

**Comment by camsim99** [comment]
Can you point me specifically to what main_activity.xml and main_activity2.xml references?

**Comment by ayyysh04z** [comment]
sure @camsim99 
main_activity.xml : https://github.com/flutter/samples/blob/main/android_splash_screen/android/app/src/main/res/layout/main_activity.xml

main_activity2.xml : https://github.com/flutter/samples/blob/main/android_splash_screen/android/app/src/main/res/layout/main_activity_2.xml

I see no use of both layouts in app ,still being used in main activity for some reason

**Comment by camsim99** [comment]
Hi @ayyysh04z sorry for the late reply! Those are both used in the splash screen animation implemented in https://github.com/flutter/samples/blob/6b6104c9c99dac534ee8fe74ceb893f4da7ffc59/android_splash_screen/android/app/src/main/kotlin/com/example/splash_screen_sample/MainActivity.kt. You can find uses of `main_activity` and `main_activity` and comments explaining how the animation works there!

Going to go ahead and close this issue as this is not relating to a bug/proposal for this repo.
