### ISSUE TITLE
Decide if we want to maintain put-flutter-to-work as a sample, as it is linked from our documentation

### ISSUE THREAD

**Issue by sethladd** [flutter/samples#2407]
From https://docs.flutter.dev/add-to-app/ios/project-setup , I found this statement: "For an example using SwiftUI, consult the iOS directory in [News Feed App](https://github.com/flutter/put-flutter-to-work/tree/022208184ec2623af2d113d13d90e8e1ce722365)."

This looks like a compelling demo/sample/example (not sure what the right words are).

We should decide: Is put-flutter-to-work a useful sample/example to maintain?

Then, based on that, we can decide:

* Do we keep referencing it from the docs?
* Do we need to update it to the best known code patterns for add2app from our docs?
* Who maintains it going forward?
* Does it move into samples/ ?

Seems good to have a nice looking add2app sample/example.

I'm filing this issue here because I don't know if anyone is monitoring "put flutter to work" repo?

**Comment by sethladd** [comment]
cc @jmagman for iOS and any context, @ericwindmill and @RedBrogdon  (for samples), @hellohuanlin (for add2app)

No coding action required. However, any context and thoughts on if we want to maintain this sample? if not, we should remove from our docs.

**Comment by hellohuanlin** [comment]
I think I discussed with Andrew before - iirc news feed repo has been archived. It was only created for an event. So no point to update it for iOS 18.

**Comment by ericwindmill** [comment]
There are currently one or two iOS samples in the pipeline. One just landed, and (I think) someone intends on adding a second. @Piinks can give you more details.

With that in mind, do we need this or additional iOS samples? In general, I would like to shoot for fewer apps that show off more features than vice-versa.

**Comment by Piinks** [comment]
> There are currently one or two iOS samples in the pipeline. 

Yes! under flutter/samples/experimental there is the date_planner app. This will continue to be iterated on. Next month I expect work will start on the second one, also in flutter/samples/experimental.

**Comment by sethladd** [comment]
Thanks all! To keep this issue focused on News Feed, sounds like that News Feed is no longer maintained.

If that's true, we should remove it from all docs (for example, see above) and clearly update the README for the News Feed app to mark it as Archived.

I'll see if there are any other feedback from folks before resolving this. When we resolve this issue, we'll open the sub-task issues.

**Comment by jmagman** [comment]
@hellohuanlin did work to make put-flutter-to-work idiomatic with SwiftUI https://github.com/flutter/put-flutter-to-work/pull/101, and I think it's our only add-to-app SwiftUI example.  Updating the add-to-app sample app https://github.com/flutter/flutter/issues/150944 should be where we invest time, and redirect website links to that instead.

**Comment by sethladd** [comment]
Thanks for the update, @jmagman !

Sounds like I'm hearing:

1) Today, as of Aug 2024, the News Feed app is our current sample/example of SwiftUI + add2app + idiomatic updated code usage

2) We want to update our formal samples in flutter/samples to update their usage of idiomatic SwiftUI add2app code

3) Once we do (2) , we can formally archive News Feed as a project and remove News Feed from our docs (in preference for our updates samples)

Let me know if I missed something.

**Comment by hellohuanlin** [comment]
> @hellohuanlin did work to make put-flutter-to-work idiomatic with SwiftUI [flutter/put-flutter-to-work#101](https://github.com/flutter/put-flutter-to-work/pull/101), and I think it's our only add-to-app SwiftUI example. Updating the add-to-app sample app [flutter/flutter#150944](https://github.com/flutter/flutter/issues/150944) should be where we invest time, and redirect website links to that instead.

@sethladd Oh I misremembered - I mistakenly said yesterday we had an outdated SwiftUI example in that repo, but actually we don't have any examples there.
