### ISSUE TITLE
Adaptive Switch sample does not compile

### ISSUE THREAD

**Issue by IanVS** [flutter/samples#2415]
Using flutter 3.24.1, I ran `flutter create --sample=material.Switch.adaptive.1 mysample`, 

When I try to `flutter run`, targeting an iPhone simulator, I get the following error:

```
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...
Xcode build done.                                            3.8s
Failed to build iOS app
Error (Xcode): lib/main.dart:123:51: Error: Couldn't find constructor 'WidgetStateProperty.fromMap'.


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.
```

**Comment by domesticmouse** [comment]
I'm failing to reproduce your results. 

```console
$ flutter run
Launching lib/main.dart on iPhone SE (3rd generation) in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         6.9s
Xcode build done.                                           16.5s
Syncing files to device iPhone SE (3rd generation)...               98ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on iPhone SE (3rd generation) is available at: http://127.0.0.1:51295/tbEgOnM6U4s=/
The Flutter DevTools debugger and profiler on iPhone SE (3rd generation) is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:51295/tbEgOnM6U4s=/

Application finished.
```

Can you please run `flutter doctor -v`?

**Comment by parlough** [comment]
It seems the `material.Switch.adaptive.1` sample was updated to use the new `WidgetStateProperty.fromMap` factory constructor on `main`. Did you perhaps run `flutter create` with a different version of `flutter`? Perhaps `beta` or `main`?

**Comment by IanVS** [comment]
This is my `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel [user-branch], 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale en-US)
    ! Flutter version 3.24.1 on channel [user-branch] at /Users/ianvs/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/setup.
    ! Upstream repository unknown source is not the same as FLUTTER_GIT_URL
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (4 available)
[✓] Network resources
```

In my flutter directory, I ran `git checkout 3.24.1`, which got me commit `5874a72aa4c779a02553007c47dacbefba2374dc`

I just tried it again, and got the same results (the failure above).  

(note the "Upstream repository unknown source is not the same as FLUTTER_GIT_URL" is due to my git config rewriting `https://github.com/` to `ssh://git@github.com/`.  I've used `FLUTTER_GIT_URL` to deal with that.)

**Comment by IanVS** [comment]
Alright, I seem to have resolved this with `git fetch && git reset --hard origin/stable`.  I'm not sure what state I had gotten into, but I probably had screwed something up since I'm new at flutter dev.  Thanks for the 👀.  

While I have you though, should I be able to change flutter versions using `git checkout <git version tag>`?  That seems to not work when I try to create samples.  For example, if I `git checkout 3.16.8`, then try to create the same adaptive switch sample, I see `Error (Xcode): lib/main.dart:109:38: Error: Type 'Adaptation' not found.`.  Are the samples always intended to be created when using the latest stable flutter version?
