### ISSUE TITLE
error in compass app, when loading images

### ISSUE THREAD

**Issue by superciccio** [flutter/samples#2543]
Hi,

Yesterday i found the compas_app example, so I decided to run it on my windows machine

in my console i see these msgs

`[HomeViewModel] Loaded user
[ImageErrorListener] Failed to load image
Exception: Codec failed to produce an image, possibly due to invalid image data.`

then in the app

![image](https://github.com/user-attachments/assets/a39ee31d-f360-4a53-abc0-b4d08b8c3cfe)

not sure if this is something you wanted and is expected or maybe something else

this is the output of my flutter doctor

PS C:\dev\programs\samples\compass_app\app> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.22631.4460], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/windows-android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.1)
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Ultimate Edition (version 2024.3)
[√] VS Code (version 1.95.3)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.

:)

**Comment by ericwindmill** [comment]
Unfortunately this is an issue with Flutter itself, per [126768](https://github.com/flutter/flutter/issues/126768).

My best advice is to upgrade to the latest version of Flutter, and use the latest versions of whichever simulators or emulators you're using to run the application.

I'm closing this issue as there is no action item for the flutter/samples repo.
