### ISSUE TITLE
Apps in flutter/samples should use the new application template

### ISSUE THREAD

**Issue by mit-mit** [flutter/samples#265]
https://github.com/flutter/flutter/pull/22565 landed a new default flutter template. This allows us to not have to check-in `android` and `ios` directories when they have just default content. We should update the app samples in https://github.com/flutter/samples to use it.

**Comment by RedBrogdon** [comment]
@domesticmouse You just did a bunch of work recreating project structure for the older samples -- are we good on this?

There should only have been a few sample apps before the Flutter Live release of the SDK.

**Comment by domesticmouse** [comment]
I believe so. I’ll rebase all the projects again when the next stable release happens.

**Comment by RedBrogdon** [comment]
(furiously scanning through GitHub history)

There were only six samples in the repo at the end of 2018. Of those, two no longer exist and three have updated metadata. Only `place_tracker`'s `.metadata` file is older than the December '18 stable release. That should reflect the last time it was updated.

So it looks like we still have a tiny yak to shave. We can get to it the next time we have a maintenance jam. We also need to update that app to use a more standard state management approach anyway.

**Comment by ericwindmill** [comment]
If I'm reading these comments correctly, the problem has worked itself out.
