### ISSUE TITLE
The place_tracker sample should use a stock state mgmt approach

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/samples#266]
The place_tracker sample in flutter/samples is using a custom InheritedWidget for state management, rather than an off-the-shelf approach. While it's fine to show folks how to write their own InheritedWidget to hold app state, place_tracker should be focused entirely on Maps.

**Comment by tusharojha** [comment]
Hey there,
@RedBrogdon do you want the place_tracker sample to be using a stock state management approach rather than custom InheritedWidget (as it is using now)?

If yes then,
I would like to work on it and switch the app to stock state management (using Stateful Widgets) from custom InheritedWidget to manage the app state.

**Comment by RedBrogdon** [comment]
It's an open issue, so we'd welcome a pull request. That said, it's important that we agree on an approach before the coding starts.

In my head, the way I imagine fixing this issue is by:

* Removing the `app_model.dart` file entirely.
* Converting the AppState class in `place_tracker_app.dart` to extend ChangeNotifier rather than be stateless.
* Using ChangeNotifierProvider to hold the AppState object for the app.

It's possible to do things another way. This is an approach used elsewhere in the repo, though, which would make it easy for folks to understand and focus on the map-related code in the sample.

**Comment by tusharojha** [comment]
I also think we should go with ChangeNotifierProvider to hold the app state as the repository follows the same.
I believe I should wrap the whole MaterialApp inside the ChangeNotifierProvider. Would that be ok sir?

**Comment by RedBrogdon** [comment]
No need to call me "sir." We're all friends here. 😄 

Yes, you'd want to have the Provider above MaterialApp so it sits above the Navigator widget that MaterialApp creates.

It sounds like you're on the right approach. Give it a try and see how it goes!

**Comment by tusharojha** [comment]
@RedBrogdon Please have a look on PR and recommend required changes. I have given an attempt to solve the issue.

**Comment by tusharojha** [comment]
@RedBrogdon I think now we can close this issue. Also, I would love to contribute more at Flutter. So if there is anything I can do then please let me know.

**Comment by domesticmouse** [comment]
Thanks for all your hard work on #424 @tusharojha! It is much appreciated.

As to future work, the real question is what interests you? There are many ways to contribute to the Flutter project, from authoring samples, blog posts, CodePen samples, YouTube videos, all the way through to creating startups using the technology to solve real problems. 

I'm not telling you to stop contributing to the Flutter samples repo, but it is worth stepping back and thinking about how you can use this tech to make yourself feel accomplished. =)
