### ISSUE TITLE
provider_shopper sample is missing login page

### ISSUE THREAD

**Issue by arnath** [flutter/samples#270]
The flutter docs at https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple describe a shopper app that has a login page. However, the sample linked (https://github.com/flutter/samples/tree/master/provider_shopper) does not have that. One of the docs or the sample should be updated to fix this.

**Comment by RedBrogdon** [comment]
@filiph Can you advise here? Was there another version of the app made for that page?

**Comment by filiph** [comment]
Well spotted. I removed the login page from the sample after code review feedback that it's not relevant to the sample — which is true (I was not using any state/data from or in the login page).

As far as I remember, the only thing that still refers to the login page is the gif at https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple. I could make a new gif recording (time permitting). Or I could add a note to the README of the sample that people should ignore the login in the gif. Thoughts? I do like the login page in the gif, as it makes the app look more real, but I understand it could be confusing.

**Comment by RedBrogdon** [comment]
Either one would resolve the issue, so whatever works best for your bandwidth is fine.

**Comment by GAyan17** [comment]
Can I work on this issue? I would like to work on it.
