### ISSUE TITLE
Create continuous build/integration samples and documentation for add-to-app

### ISSUE THREAD

**Issue by xster** [flutter/samples#271]
We currently have https://flutter.dev/docs/deployment/cd and partners like CodeMagic for full-Flutter CI instructions but it's not clear how to do add-to-app CI. Create documentation and samples demonstrating add-to-app CI. 

cc @RedBrogdon

**Comment by RedBrogdon** [comment]
This is in progress. We now have Travis building each Android and iOS add-to-app example in the repo.

The next stage is working with @collinjackson to get [espresso](https://pub.dev/packages/espresso)-based tests working for Android. iOS will follow that.

**Comment by Bhavay192** [comment]
hey @RedBrogdon  I would like to work on this issue , can u help me with how can I resolve this ?

**Comment by ericwindmill** [comment]
Now that we have add-to-app samples which have CI, and the CI page on the website has been greatly expanded, I'm closing this as complete.
