### ISSUE TITLE
[codelabs] !_debugLocked': is not true. on hot reload

### ISSUE THREAD

**Issue by jrutley** [flutter/samples#275]
## The Problem

Once this error occurs, you have to stop the app before performing any more hot reloads:
![image](https://user-images.githubusercontent.com/771365/71230349-504ffb80-22b7-11ea-9aaa-899f9f27f125.png)

## Steps to Reproduce

I've been going through the Flutter tutorial at this point (https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5)

Dart file here: [Rename to main.dart](https://github.com/flutter/flutter/files/3986722/main.dart.txt)

1. Run main.dart using either Android emulator or iOS emulator
2. Verify that it's working
3. Uncomment lines 71-82
4. Save file (hot reload)
5. Observe that the code fails. (I don't yet know why this doesn't work, but I digress)
6. Comment lines 71-82
7. Save file

**Target Platform: Android and iOS**
**Target OS version/browser: Android API 29 x86**
**Devices: Nexus 5X emulator, iPhone 11 Pro Max emulator**

## Logs

Sorry it's not verbose, but it looks like it's related to hot reload.

```Initializing hot reload...
Syncing files to device Android SDK built for x86...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#5e8f2](dirty, state: NavigatorState#90e6e(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/jeramy/Projects/flutter/car_games/lib/main.dart:10:12
When the exception was thrown, this was the stack: 
flutter/flutter#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2330:12)
flutter/flutter#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
flutter/flutter#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
flutter/flutter#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
flutter/flutter#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 531 libraries in 2,062ms.
```

```
```

```
jeramy@Jeramys-MacBook-Pro car_games $ flutter analyze
Analyzing car_games...                                                  
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Users/jeramy/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jeramy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jeramy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!```

**Comment by RedBrogdon** [comment]
@jrutley There are definitely times when hot reload can cease working. An example of this is when you change a StatelessWidget class to extend StatefulWidget instead -- hot reload replaces the widget, which then looks for a state object, can't find one, and freaks out. The tools team is working on this and some other common scenarios.

I'm curious, though. When you ran into this problem initially, did you try a hot restart as well, or just a hot reload?

**Comment by jrutley** [comment]
I'm afraid I can't remember @RedBrogdon sorry. I believe it was just the hot reload -- whichever one happens automatically from within Android Studio on save.

**Comment by RedBrogdon** [comment]
Got it. Thanks for the response, and thanks for filing the issue.

I believe the root problem here is that the difference between hot reload, hot restart, and full restart isn't always clear to new developers. We have a [dedicated guide](https://flutter.dev/docs/development/tools/hot-reload) for it, but it's an easy thing to miss, especially when first starting out.

Since that isn't a samples-related problem, nor is it a problem specific to that codelab, I'm going to go ahead and close this issue out. We're doing some planning for our next round of resources, though, and I'll make sure the different types of restarts gets aired as something that could use more exposure.
