### ISSUE TITLE
[Veggieseasons] Let the search page feed slide behind the search/tab bar

### ISSUE THREAD

**Issue by xster** [flutter/samples#278]

**Comment by RedBrogdon** [comment]
Notes:

Right now the list on the search page is clipped by the bottom edge of the search field. Instead, it should slide underneath the list.

**Comment by AyushBherwani1998** [comment]
I would like to work on this issue @RedBrogdon 
We can have a stack where we can place the search bar above the list view. Is there any alternate solutions that can be tried to achieve this? I'll be happy to get some leads.

**Comment by xster** [comment]
I think this got fixed recently?

**Comment by RedBrogdon** [comment]
#279, which was the status bar-related scroll, got fixed. This is still outstanding.

**Comment by tusharojha** [comment]
@RedBrogdon One possible way could be to wrap the items inside a column and provide the singlechildscrollview at the very top of both search bar and feeds.

Can I do this way or would you like to suggest something?

**Comment by RedBrogdon** [comment]
I think this would need something slightly more sophisticated, unless I'm misunderstanding you.

The goal here would be for the search bar to remain in place at the top of the page, and for the search results to slide underneath it when scrolled up.

**Comment by tusharojha** [comment]
I would like to work on this issue!
@RedBrogdon I have tried to use stack instead of column inside the `search.dart` (output as shown below). Although I don't think its the exact result but would like to know your thoughts on the same.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/36601970/93668224-c680c900-faa8-11ea-9460-3083cc4d10d5.gif)

**Comment by tusharojha** [comment]
@RedBrogdon I would like to know your suggestions for its implementation. Please have a look into it.

**Comment by kjain333** [comment]
There seems to be a simple bug in screen recording you have shared that the first item of the list is already covered by the search bar may increasing the size of the listview by one and adding a SizedBox at the starting can fix this issue.

**Comment by kjain333** [comment]
I request @xster and @RedBrogdon to kindly review the pull request I have created recently

**Comment by RedBrogdon** [comment]
This has been fixed in #572.
