### ISSUE TITLE
[Veggieseasons] Main feed shouldn't scroll behind status bar

### ISSUE THREAD

**Issue by xster** [flutter/samples#279]
See the iOS App Store. There's a static background bar behind the status bar as the feed is scrolled up.

**Comment by RedBrogdon** [comment]
Notes:

The status bar should remain with an opaque background, with list content going underneath it unseen.

Alternately, the status bar could use a frosted glass effect.

**Comment by ManasviPatidar** [comment]
@RedBrogdon, I think my PR #337  satisfies the required conditions. The result is:-

![untitled](https://user-images.githubusercontent.com/43138335/75517693-4ec45180-5a25-11ea-85f7-cb26ecedf283.gif)
