### ISSUE TITLE
Push a bitcode enabled app to test flight

### ISSUE THREAD

**Issue by dnfield** [flutter/samples#281]
Now that Bitcode is available for Flutter apps, we'd like to measure what the store actually produces for an IPA.

@RedBrogdon - could we create a build of Veggie Sessions or similar with bitcode enabled, publish it ot test flight, and measure it on some device(s)?  I'd be happy to sit with you on this if it helps.

**Comment by RedBrogdon** [comment]
@dnfield I remember testing a build of veggieseasons with you. Did that verify this issue, or was it something else?

**Comment by dnfield** [comment]
That was for something else unfortunately.

**Comment by RedBrogdon** [comment]
I pushed a bitcode-enabled version of Veggie Seasons up to TestFlight:

https://github.com/flutter/samples/pull/305

No warnings were received from iTunes/Apple, so I'm calling this one a win.

**Comment by dnfield** [comment]
Woohoo!
