### ISSUE TITLE
Target of URI doesn't exist: 'package:gallery/l10n/gallery_localizations.dart

### ISSUE THREAD

**Issue by santiagosuarezecheverri** [flutter/samples#296]
I don't exist the package

**Comment by RedBrogdon** [comment]
Can you tell us a little more about when you saw this error? What were you trying to do, for example, and with which sample?

**Comment by santiagosuarezecheverri** [comment]
Thanks for writing, I am trying to make the flutter gallery example banner, I wrote the code as is and the error is an address that is not found, the strange thing is that I have it in the right direction and it does not grab the package.
Thanks for writing, I am trying to make the flutter gallery example banner, I wrote the code as is and the error is an address that is not found, the strange thing is that I have it in the right direction and it does not grab the package.
![Captura2](https://user-images.githubusercontent.com/9156550/73848993-261ab480-47f7-11ea-826b-a870779e2538.PNG)
![Captura3](https://user-images.githubusercontent.com/9156550/73849183-7f82e380-47f7-11ea-93d5-e67f53ab7146.PNG)

**Comment by farheen21** [comment]
Hey!!! did you add the dependencies to pubspec.yaml file? if not then add this to your pubspec.yaml file
`dependencies:
sdk: flutter
flutter_localizations:
sdk: flutter
flutter_cupertino_localizations: ^1.0.1`

**Comment by RedBrogdon** [comment]
@rami-a, now that the Gallery has moved to its own repo, I'm going to close this. Wanted to make sure you saw it, though.

**Comment by 3boodd** [comment]
> Hey!!! did you add the dependencies to pubspec.yaml file? if not then add this to your pubspec.yaml file
> `dependencies: sdk: flutter flutter_localizations: sdk: flutter flutter_cupertino_localizations: ^1.0.1`

its not working with me either

![image](https://user-images.githubusercontent.com/36028899/85655478-d9554e80-b6af-11ea-9bfb-661142cbb1db.png)

**Comment by NElnour** [comment]
> > Hey!!! did you add the dependencies to pubspec.yaml file? if not then add this to your pubspec.yaml file
> > `dependencies: sdk: flutter flutter_localizations: sdk: flutter flutter_cupertino_localizations: ^1.0.1`
> 
> its not working with me either
> 
> ![image](https://user-images.githubusercontent.com/36028899/85655478-d9554e80-b6af-11ea-9bfb-661142cbb1db.png)

Hey, I got it to work. Just follow installation instructions for flutter gallery package found here: https://pub.dev/packages/flutter_gallery/install.

Good luck!
