### ISSUE TITLE
Veggieseasons sample drops frames while scrolling

### ISSUE THREAD

**Issue by kobutri** [flutter/samples#297]
I noticed that the veggieseasons sample app drops below 60fps while scrolling through the veggies on the home screen.
I get an average of around 20ms/frame GPU time and max GPU time of around 30 ms/frame.
So it only runs about 50fps, which seems like a small deviation but on a fixed refresh display it leads to micro stuttering.

### Test Setup:
Flutter 1.7.4 release build.
I turned on the performance overlay by adding to `showPerformanceOverlay: true` to the `CupertinoApp` widget. 
I testest both on a Galaxy S8 with Android 9.0
and a iPad 6th generation running iOS 12.3.1
Both had similar frame times.

I know that these are not fastest devices but it is just a simple list after all and I would expect scrolling to be smooth.

**Comment by RedBrogdon** [comment]
CC: @HansMuller 

Clearly we needed our own issue tracker for the samples for a while now.

I don't have an iOS hardware device on me today, but I'll try to verify if this problem still exists with the current SDK.

**Comment by ericwindmill** [comment]
Given that Flutter on iOS uses an entirely new rendering engine today, I'm closing this comment as outdated.
