### ISSUE TITLE
plattform_view demo code does not work

### ISSUE THREAD

**Issue by atjosue** [flutter/samples#330]
When you try to run the test application, it opens and closes immediately.
Attached to this comment the data of my work environment and I would like to point out that I have already tried with the most recent version of Dart and Flutter and it did not work so I decided to make a downgrade.

iMac:platform_view_swift red5g$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-SV)
    • Flutter version 1.12.13+hotfix.5 at /Users/red5g/Documents/development/flutter/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/red5g/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/red5g/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.44.0.9-CA-macosx) (build 1.8.0_242-b20)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Users/red5g/Library/Android/sdk/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/red5g/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (1 available)
    • iPhone • 8f90f344ac80f6853eadb60e634ef2cb7b39232a • ios • iOS 13.3.1

I will be aware of this problem since my project depends on this.
Thank you

**Comment by RedBrogdon** [comment]
Thanks for filing a bug, @atjosue.

I haven't been able to replicate this locally. Can you tell me what kind of crash you're seeing, and paste in whatever log file output you see when it occurs?

**Comment by jddeep** [comment]
@RedBrogdon should I give this a look and see if it is reproducible at my end?

**Comment by RedBrogdon** [comment]
Sure. Let us know what you find.

**Comment by jddeep** [comment]
I think we can close this issue. The very sample app runs fine on my device. No such crashes as mentioned. Also, the issue author has not provided any more insights to what he might have referred to through this issue :thinking:

**Comment by RedBrogdon** [comment]
Nice to know it's working for someone else.

The repo has an issue management bot that will automatically close the issue if no feedback is provided by the author within two weeks, so no worries there. If anyone *is* still having an issue with this sample, of course, please let us know!

**Comment by atjosue** [comment]
ok, sorry for dont ask before, but i was busy some days.
y tried to run the Flutter PlattformView Example on an Iphone 6s IOS 13.3.1 but the app don't start, only show a white screen for a milisenconds before close it. The output console only show the message "installing and launching..." .
that is the flutter doctor -v output for it phone.

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-SV)
    • Flutter version 1.12.13+hotfix.5 at /Users/user/Documents/development/flutter/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Users/user/.sdkman/candidates/java/current/bin/java
    • Java version OpenJDK Runtime Environment (Zulu 8.44.0.9-CA-macosx) (build 1.8.0_242-b20)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Users/user/Library/Android/sdk/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Users/user/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] Connected device (2 available)
    • iPhone de Rosa • ab694243cb3ac9bcdf9410dea38d41ccf26e8db1 • ios • iOS 13.0
    • iCiensprog     • 8eb1337cb597f305f0433626dab8ba050e4bce8e • ios • iOS 13.3.1

! Doctor found issues in 1 category.
I would like to comment that i tried on an iphone 6s IOS 13.0 and work perfectly. 
Thanks for ask my issue you are an excellent team. (Y)
