### ISSUE TITLE
doc bug: Missing samples in Experimental sample doc

### ISSUE THREAD

**Issue by jddeep** [flutter/samples#360]
doc bug: Missing samples in Experimental sample doc

Here is the index - https://github.com/flutter/samples/tree/master/experimental#index

We need to update this with `desktop_photo_search` and `web_dashboard` content as well.

**Comment by jddeep** [comment]
@RedBrogdon @kwalrath Thoughts? Let me know, I shall fix this up.

**Comment by RedBrogdon** [comment]
Ah, that's a good catch. I've filed a quick PR to remove the index from that README. It's redundant, which is likely the reason we've been forgetting to update it.

**Comment by jddeep** [comment]
Cool. The PR LGTM :)
