### ISSUE TITLE
sample repo for data persistence

### ISSUE THREAD

**Issue by AjayThakur12** [flutter/samples#361]
@RedBrogdon  can I add sample repo which shows how to use data persistence using SQFlite .

**Comment by RedBrogdon** [comment]
First, thanks for filing an issue prior to starting work. It's much easier to have a conversation *before* the PR is sent. :)

I would ask that you not add any new samples to the repo, for a couple reasons:

* This repo isn't meant to be an "official" set of samples for Flutter. There isn't one! There are many samples created in other repos that are just as good as what's found here, and we support that.
* This repo is already too big. It takes a *long* time to clone, and adding a new app would make that problem worse.

If you have an idea for a new sample, just build it in a repo of your own. You can add it to the list of samples in [Awesome Flutter](https://github.com/Solido/awesome-flutter), and if you tweet about it, I'll be happy to help spread the word. 😄
