### ISSUE TITLE
bug: dialog message and action buttons unsuitable for logout

### ISSUE THREAD

**Issue by jddeep** [flutter/samples#363]
## Adaptive Music App screenshot: (in platform_design)

<img src="https://user-images.githubusercontent.com/43133646/76283439-9a49eb80-62c0-11ea-9296-c541c1304d70.png" width=300 />

One solution could be to have a landing page (login-like page) for new users so that we can use that page on logging out as well. Currently, we directly land on the homepage having the list of songs.
We also need to update the logout dialog message and buttons - "Go back" and "cancel" pretty much makes the same meaning to me.
 OR
We could remove the Log out button itself from the profile screen as it is pretty much unfunctional otherwise.

**Comment by jddeep** [comment]
@RedBrogdon @kwalrath @johnpryan Thoughts? Let me know if could go ahead with this.

**Comment by RedBrogdon** [comment]
I think this might be a miscommunication. The logout form in the app is really just an excuse to show how different types of alerts work. The idea is that people seeing it will understand that it's not real.

If you'd like, you could change the text displayed in the alert from "You may check out any time you like, but you can never leave" to something like "You can't actually log out! This is just a demo of how alerts work." and the "Go back" button to "Got it". That might make things clearer for some readers.

**Comment by jddeep** [comment]
@RedBrogdon Agreed! Although most of the things in the app are for showcase/demonstrating purposes, this "Log out" button seemed a bit confusing especially with those buttons and the message.
Will send a PR updating this ASAP. Thanks :)
