### ISSUE TITLE
[animations] Add AnimatedWidget sample - FadeTransition

### ISSUE THREAD

**Issue by jddeep** [flutter/samples#370]
Missing animation samples of various Animation widgets.

@RedBrogdon @johnpryan Do we plan to add samples of widget animations like [FadeTransition](https://api.flutter.dev/flutter/widgets/FadeTransition-class.html), [DecoratedBoxTransition](https://api.flutter.dev/flutter/widgets/DecoratedBoxTransition-class.html), [RotationTransition](https://api.flutter.dev/flutter/widgets/RotationTransition-class.html), etc.

If yes please do let me know. Would love to add samples for them here.

**Comment by johnpryan** [comment]
Yeah this is a good idea. These widgets are almost all subclasses of [AnimatedWidget](https://api.flutter.dev/flutter/widgets/AnimatedWidget-class.html). I would make this `#8` in the `basics/` and stick to a very simple demo.

Thanks!

**Comment by jddeep** [comment]
Cool so I'll be sending a PR with a FadeTransition demo first. In the same screen we can have different buttons for different transitions. The demo shall be simple indeed. Is that cool or you plan something else?

**Comment by johnpryan** [comment]
We don't need all the transition widgets, just one example of an AnimatedContainer. Providing a link to AnimatedWidget will let users discover more *Transition widgets.

**Comment by jddeep** [comment]
Cool. I'll send a PR and let's see if any other improvements can be made :)

**Comment by RedBrogdon** [comment]
Thanks for filing an issue so we could check in before coding started, @jddeep!
