### ISSUE TITLE
[veggieseasons] Android subproject should be removed.

### ISSUE THREAD

**Issue by aadarsh-patel** [flutter/samples#372]
On the details screen, when users tap the back button of the device, the app gets closed instead of navigating back to the home screen.
Back button should behave like the close button given in the header section of the details screen.

![veggie_bug](https://user-images.githubusercontent.com/53324291/76656032-c1d8d680-6594-11ea-8cd5-7a07eaadcd62.gif)

**Comment by aadarsh-patel** [comment]
If this is a valid issue then i would like to work on it.

**Comment by RedBrogdon** [comment]
Thanks for filing this issue. The problem here is that Veggieseasons isn't designed or intended to be run on Android. Because Flutter is multiplatform, it *will* run, but it doesn't make sense for us to invest time in the Android experience. 

What should be done instead is:

* Remove the `android`  directory within the project
* Add `android` to the .gitignore in the project directory, so it won't return.

Doing both in one PR requires a little git trickery, but if you're up for it, please feel free to file one.

**Comment by aadarsh-patel** [comment]
Sure. I'll try.
Time for some github tutorials

**Comment by aadarsh-patel** [comment]
Hey @RedBrogdon ,
Just saw the description of VeggieSeasons app, There it is clearly mentioned that 
>  This application is designed specifically for iOS to showcase Cupertino package.
> It's not intended to be run on Android, web, or desktop.

This issue opened by me is nothing but a silly mistake.
VeggieSeason is a cool app that also showcases how to use `models`, `shared_preference,` etc. which is useful for android developers as well.

Due to the above reasons I don't think removing android support will be a good idea for the app.
And hence i am closing this issue.

**Comment by aadarsh-patel** [comment]
Sorry for closing this issue without waiting for your response.

**Comment by jddeep** [comment]
Removing the directory from the sample isn't ideal. Is it? :thinking: At least devs can get a feel of the sample if they have an android device with them solely. What do you think?

**Comment by RedBrogdon** [comment]
Thanks for reopening, @aadarsh-patel. 

Removing the Android subproject doesn't make it *impossible* to build and run the app for Android. All you'd need to do is run `flutter create .` from within the project directory, the directory would be recreated in your local copy, and then you'd be ready to go.

What it *does* do is prevent confusion about how we intend for the app to be used. Its primary purpose is to show how to use widgets from the Cupertino package to build UI that looks at home on an iPhone. While can still be useful as a model for handling user preferences and some data, it was written first and foremost to be run on iOS devices, and it isn't tested (nor make sense, really) anywhere else.

By removing the `android` directory, we can prevent beginners from getting confused about what the app is meant to do and getting annoyed when it doesn't work quite right on platforms other than iOS, while still allowing advanced users (who know enough to `flutter create .`) the opportunity to test the app on those platforms.

**Comment by aadarsh-patel** [comment]
Closing this issue as it has been resolved by PR https://github.com/flutter/samples/pull/378
