### ISSUE TITLE
[platform_design] Some of the UI elements turn invisible in dark mode

### ISSUE THREAD

**Issue by abd99** [flutter/samples#376]
I found the following issues in the platform_design app:
- The Settings show black on black text in dark mode.
- There are a couple of more widgets that don't go well with the dark mode throughout the app.

Screenshots:
![Screenshot_20200317-000736](https://user-images.githubusercontent.com/30566863/76789764-7d8f4580-67e3-11ea-855c-f7f930ac07ac.png)
![Screenshot_20200317-000747](https://user-images.githubusercontent.com/30566863/76789789-854eea00-67e3-11ea-8cb1-41a3af400f01.png)

I'm currently working on the solution. 

I've read the contribution guide but this is my first PR in a big repo. So, please bear with me.
I'm thinking of just changing color to grab from the theme wherever it is hardcoded.

Let me know what you think of it @RedBrogdon @johnpryan @domesticmouse

**Comment by jddeep** [comment]
This has been an issue for the iOS version of VeggieSeasons app as well. There is already an issue open about that #322. @RedBrogdon should we toggle the app font colors with respect to the app theme brightness(light or dark).

**Comment by RedBrogdon** [comment]
There are a few things that should happen here:

1) Audit all the apps in the repo to make sure there aren't any others with dark mode problems, and file issues for them.
2) Hard-code a bright theme for any that do, this app included. See #340 for how this was done for Veggieseasons.
3) Update each of those apps to properly respect dark mode.

That third task is the hardest, and for each app it should be done in several PRs rather than just one big one. It's too large a change to review otherwise.

**Comment by abd99** [comment]
As per your suggestion @RedBrogdon, I have checked all the apps in the repo except for web and experimental apps for dark mode problems. As of now, none of the apps have that problem except for VeggieSeasons(which you solved temporarily). Most of them don't even support dark mode. Let me know if you want me to add dark mode support to any of them. I have started working on the fix for VeggieSeasons and have shared the solution I'm opting for in #322. Please let me know what you think of it.

**Comment by RedBrogdon** [comment]
@abd99, is there any remaining short-term work for VeggieSeasons now that #322 is merged? I believe we can go ahead and close this if not.

**Comment by abd99** [comment]
I think we are good for now. I'll close this issue
