### ISSUE TITLE
Update the navigation rail sample once the component officially lands

### ISSUE THREAD

**Issue by clocksmith** [flutter/samples#383]
Once https://github.com/flutter/flutter/pull/49574 lands, https://github.com/flutter/samples/blob/master/experimental/web_dashboard/lib/src/widgets/third_party/adaptive_scaffold.dart should be updated

**Comment by RedBrogdon** [comment]
@johnpryan, I imagine this is already part of your plan for the web sample, so I'm assigning it to you.

**Comment by johnpryan** [comment]
👍 looking forward to making this change
