### ISSUE TITLE
add-to-app create an explicit example of launching a flutter screen with prepopulated data

### ISSUE THREAD

**Issue by xster** [flutter/samples#384]
This is pretty much what you have already, but right before presenting a flutter view, invoke a channel message to send something.

**Comment by jddeep** [comment]
Good Idea. This is also something we want to achieve through the new "platform channel sample app" idea. @RedBrogdon what do you think?

**Comment by xster** [comment]
That's a good idea. We can do a 2 in 1 of showing pigeon and doing data passing on launch/dismiss in one demo. 

cc @gaaclarke

**Comment by SatYu26** [comment]
@xster i would like to know how to approach to solving this issue. If possible !

**Comment by xster** [comment]
It's on Android only currently but there's a demo to that effect in https://github.com/flutter/samples/tree/master/add_to_app#android_books-and-ios_books-todo

**Comment by ericwindmill** [comment]
The add_to_app/books sample now achieves this on both iOS and Android
