### ISSUE TITLE
[visual sample index] Clarify samples vs demos

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#390]
This could be something simple like a tooltip, or an explanation on the page.

**Comment by cv692001** [comment]
Hey @RedBrogdon @johnpryan  I am very new to open source contribution and I just want to get started with my first contribution can you please help me out 👍

**Comment by tusharojha** [comment]
@johnpryan After going through the latest visual samples index. It clarifies which are samples, demos & cookbooks. So, I think we can close this issue now.

**Comment by johnpryan** [comment]
@tusharojha Good catch, thanks!
