### ISSUE TITLE
[visual sample index] Add Carousel

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#393]
Design spec:

<img width="896" alt="Screen Shot 2020-03-23 at 2 18 19 PM" src="https://user-images.githubusercontent.com/1145719/77364138-2b817f00-6d11-11ea-837b-332c67734aa9.png">

**Comment by RedBrogdon** [comment]
😍

**Comment by mohak852** [comment]
@RedBrogdon  I wanna work on this issue if for this issue no PR is submitted I wanna work on this issue

**Comment by mohak852** [comment]
@johnpryan Can you provide me the images and the fonts used in this design.

**Comment by johnpryan** [comment]
@mohak852 The code is here: https://github.com/flutter/samples/tree/master/web/samples_index

**Comment by cazci** [comment]
hi @mohak852, are you still working on this? If not may I take a look :)

**Comment by johnpryan** [comment]
Deployed: https://flutter.github.io/samples/gallery.html
