### ISSUE TITLE
Remove repo-wide gitignore file

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/samples#397]
Now that we have so many individual projects, some of which are traditional Android and iOS apps, we need to remove the repo's overall .gitignore and standardize the project-level ignore files.

**Comment by arteevraina** [comment]
Hello @RedBrogdon I want to start my contribution to this repo. Can I take up this issue?

**Comment by RedBrogdon** [comment]
In addition, the gitignores for each sample should be checked to make sure they match the ones currently created by `flutter create`.

**Comment by Bhavay192** [comment]
Hello @RedBrogdon  I would like to work on this issue , can u help me with any way possible please ??
