### ISSUE TITLE
[animations] Update  README.md 

### ISSUE THREAD

**Issue by AyushBherwani1998** [flutter/samples#398]
## Description 

The basic animation section in the app has two new examples, `AnimatedPositioned` and `AnimatedSwitcher` which hasn't been updated in the README.md.

**Comment by jddeep** [comment]
@RedBrogdon I believe, we can close this. This has been fixed.

**Comment by AyushBherwani1998** [comment]
Yes @jddeep we can close it. The issue has been resolved. Thanks for pointing :)
