### ISSUE TITLE
Animated Container overflows on right

### ISSUE THREAD

**Issue by attex** [flutter/samples#431]
Hi guys, 

i am using a Animated Container to move some text from left to right. 
Therefore I use a variable `currentPositon` and a `positionPadding` which ist 30. 
So for the increasing currentPosition the container moves 30 points to the right. But my problem is, that there is no limit. As a result the container just overflows the right and i need it to stop before it overflows.

![WhatsApp Image 2020-05-06 at 08 37 35](https://user-images.githubusercontent.com/9304272/81144723-f190d300-8f74-11ea-99eb-eec054e8cc09.jpeg)

Thanks in advance

att3x

**Comment by johnpryan** [comment]
Hi @attex, this looks more like a question for StackOverflow. Also, if you include some code you are more likely to get a helpful answer. Thanks!
