### ISSUE TITLE
Flutter benchmark

### ISSUE THREAD

**Issue by janat08** [flutter/samples#434]
https://github.com/krausest/js-framework-benchmark/issues/687
Please submit sample for benchmark linked above. you're not declaring any performance metrics, as is basically customery even if it's crap as you have no idea what you're being compared against.

**Comment by RedBrogdon** [comment]
I'm not actually familiar with the site you listed, and I don't believe anyone on the team at the moment has the bandwidth to go through the integration process.

That said, Flutter does performance testing with each commit. If you're interested in how things are going, we have a Cirrus dashboard with all the latest test results:

https://cirrus-ci.com/github/flutter/flutter/master

**Comment by janat08** [comment]
By in large it's just something like just creating a crud table.
