### ISSUE TITLE
Provide samples for redux

### ISSUE THREAD

**Issue by mehrdad-shokri** [flutter/samples#438]
I know there are some open source apps following the redux pattern for state management. 
I've also watched some IO conferences which flutter maintainers mentioned they use both bloc and provider pattern in their apps. 
I wanna know that if flutter maintainers see redux a good pattern for a flutter or not? Since [it's library](https://pub.dev/packages/flutter_redux) has been favorited I guess the answer is yes, but could you explain the pros and cons of each pattern?

**Comment by RedBrogdon** [comment]
Redux is definitely a state management approach that's working for Flutter developers, though it's one of many. We don't really have the engineering bandwidth to give all the possible state management options a dedicated sample, so we've mostly standardized on Provider and ChangeNotifier for our samples. It's a good "first" state management approach, and can help folks get enough Flutter coding under their belt that they're ready to look at the other, more advanced patterns and pick the one that suits them.

So the short answer here is "Yes, redux is definitely a great pattern, but we don't have the time or space to cover *every* possible pattern, so we've tried to avoid favoring any of them."

I can point you (or anyone else reading this) to some good Redux resources, though.

First, Brian Egan, the maintainer of `flutter_redux`, also maintains the [Flutter Architecture Samples](https://fluttersamples.com/), which are a great resource for seeing how the various state management libraries for Flutter differ from one another.

There are also some good docs and videos out there on state management, such as:

* The [flutter.dev guide](https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro) for state management.
* An [I/O '19 talk](https://www.youtube.com/watch?v=d_m5csmrf7I) on state management covering several options. 
* Brian Egan's [DartConf talk](https://www.youtube.com/watch?v=zKXz3pUkw9A) on the subject
