### ISSUE TITLE
Provide a Feature CodePen category to the samples page

### ISSUE THREAD

**Issue by csells** [flutter/samples#439]
Current the https://flutter.github.io/samples/# page Sample, Cookbook and Web Demos categories. It would be great to add a CodePen category, too, to surface particularly wonderful Flutter CodePens, e.g. like these from Mariano: https://codepen.io/mkiisoft

**Comment by RedBrogdon** [comment]
Starting this as a p2, expecting it to get bumped up to p1 in the near future.

@johnpryan, I think I mentioned this issue to you in a 1:1, but I'll `@` you here just to make sure you see it again. 😄 

Adding CodePen seems like a great idea. My only concern would be to consider DartPad links, CodePen links, and anything else that we might add in a holistic way.

**Comment by ericwindmill** [comment]
Closing, as the samples index is being deprecated
