### ISSUE TITLE
peanut build shows auto-generated page

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#455]
<img width="1115" alt="Screen Shot 2020-06-01 at 5 19 42 PM" src="https://user-images.githubusercontent.com/1145719/83466496-1a996c00-a42c-11ea-9988-b7c6115020e3.png">

Currently, we copy the contents from samples_index into the built directory (https://github.com/flutter/samples/blob/master/web/_tool/peanut_post_build.dart). This is running *after* peanut runs, so I'm not sure why we're still getting the index.html file that peanut generates.

cc @kevmoo do you know what might be causing this?

**Comment by kevmoo** [comment]
Uh. I'd have to look at your script.

**Comment by johnpryan** [comment]
no worries, I will take a look.
