### ISSUE TITLE
We should add navigationRail in flutter

### ISSUE THREAD

**Issue by mohak852** [flutter/samples#477]
So as you know the flutter has come with a new feature which is navigationRail in flutter latest version.

I wanna work on this issue

**Comment by domesticmouse** [comment]
We currently have one [desktop sample](https://github.com/flutter/samples/tree/master/experimental/desktop_photo_search). One option is to figure out how to add a navigation rail to that sample. Another option is add a new sample, but I'd like to understand what your new sample will communicate to our sample readers.
