### ISSUE TITLE
Clarification on code

### ISSUE THREAD

**Issue by abhimanyunaikare** [flutter/samples#498]
In the Catalog model dart file, inside the Item class, there is the following code.

`
  @override
  bool operator ==(Object other) => other is Item && other.id == id;`

Would someone please explain this. What does it do? I have no understanding here. Thanks

**Comment by RedBrogdon** [comment]
The issue tracker for the repo is intended for folks who need to report bugs or breakages in the apps. For questions about how the code works, you're better off trying the [Flutter](https://flutter.dev)/[Dart](https://dart.dev) websites, [StackOverflow](https://stackoverflow.com/questions/tagged/flutter), or the [Flutter Dev Google Group](https://groups.google.com/forum/#!forum/flutter-dev).

In this case, though, I can answer your question here. That line is an override for the equality operator in the `Item` class in provider_catalog. It's defining the standard Dart should use to determine whether two instances of `Item` are equal. By default, this is [done by reference](https://api.dart.dev/stable/2.8.4/dart-core/Object/operator_equals.html), but the author of the app wants it instead to be done by comparing `id` values.

### @override bool operator ==(Object other) 
This is the signature for doing the override. It's a way to tell Dart "I'd like to define specific behavior for `==`."

### => 
This is arrow syntax. It's telling Dart that the `==` should simple return the value of the expression to follow.

### other is Item 
This checks that the object to which an instance of `Item` is being compared is, in fact, another `Item`. If it's a String or a number or something, this comparison immediately returns false.

### && other.id == id;
This check (done after the type check), compares the id values of the two `Item`s, and returns true if their `id` values match.

The end result of all this is that two separate instances of `Item` will be considered equal as long as they have the same value in their `id` fields.
