### ISSUE TITLE
State of NoData in infinite list App

### ISSUE THREAD

**Issue by pedia** [flutter/samples#514]
@filiph 
Thanks for this great example.

How to express state of NoData?

Thanks.

**Comment by filiph** [comment]
Hi @pedia, could you elaborate on what you mean? What class or part of the sample are we talking about?

**Comment by pedia** [comment]
Hi @filiph,

In real world, function `fetchPage`
```dart
  Future<ItemPage> fetchPage(int startingIndex) async
```
maybe return empty like `ItemPage(items: [])`. In this situation, the App crash now.

My question is How to judge no-data state in `Catalog`? Normally we should present a view of `Text('No Data Yet')` now.

PS: There are so many solutions for infinite list, but I think this way is most simple and lightweight. So I really want use this code in product app.

Thanks. Sorry for my pool english.

**Comment by pedia** [comment]
Happy resolved this with `itemCount` and make this a [library](https://pub.dev/packages/infinite_pagination)

Thanks @filiph
