### ISSUE TITLE
we should remove fav items from home page

### ISSUE THREAD

**Issue by mohak852** [flutter/samples#543]
in the testing app we should remove the items that we are added in the favorites.

**Comment by abd99** [comment]
Thanks for filing an issue @mohak852!

Every sample in the repo has a set of goals. The main goal of the testing app is to demonstrate how to write different types of tests for a Flutter app. It doesn't feel like the suggested change would contribute towards the goals of the sample. Also, all the samples are built in the easiest and the most unclever way possible, avoiding all the unnecessary things. This makes it easier for anyone going through the code to learn from it. Just for the record, a catalog always contains all the items no matter they've been added to any custom list(favorites list in this case) or not.

If you come across something that can be improved in the repo that contributes towards a sample's goal or something like #540, feel free to file more issues.

**Comment by mohak852** [comment]
Thanks @abd99 for replying me!
