### ISSUE TITLE
[VeggieSeason] We should add a exit dialog in veggieseason app.

### ISSUE THREAD

**Issue by mohak852** [flutter/samples#546]
[VeggieSeason] In this app we should add an exit dialog in the homepage.

@abd99 @AyushBherwani1998 @RedBrogdon

**Comment by mohak852** [comment]
@abd99 @AyushBherwani1998 Have you go through this issue.

**Comment by RedBrogdon** [comment]
Can you give us a little more info on your rationale? I don't know that we have exit dialogs in any of our other samples, for instance.

**Comment by mohak852** [comment]
![maxresdefault](https://user-images.githubusercontent.com/58987025/93591941-e80d8200-f9ce-11ea-8b9c-93f4e1458de8.jpg)
Like this Dialog as shown in this picture If we want to exit the app, we should have an alert dialog that confirms that are you sure you want to exit the app or not

**Comment by mohak852** [comment]
@RedBrogdon Should I go with the Dialog Box.

**Comment by RedBrogdon** [comment]
I think that showing a dialog box could be a good thing. It's the idea of an exit button that's giving me pause. Is there another location in the app where it would make sense to add a dialog?

**Comment by mohak852** [comment]
No sir i think the homepage will be fine Because if we implement this inside any other page it will not make any sense. @RedBrogdon

**Comment by RedBrogdon** [comment]
Sorry, what I meant was, is there another type of dialog that might make sense for the app? A dialog to confirm some other choice?

**Comment by kjain333** [comment]
Respected Contributors,
It's been few months since I have contributing to flutter applications and now wanted to dive deeper into it by contributing to open source projects. I found this issue really interesting to begin with but since it's my first time here I just wanted some guidance if this issue will be fine to begin with and a little more about how the checks are performed before merging any pull request.

**Comment by tusharojha** [comment]
Hi @kjain333 <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="24px" alt="hi">
Thanks for your excitement in contributing to Flutter Samples. Also, Flutter Community always respects the new contributors.

Regarding this issue, @RedBrogdon is trying to say that we need a perfect use-case for implementing a bottom sheet from a user's perspective. So, I would suggest using the app and find the right slot for a bottom sheet.

Also regarding the checks in pull requests, the following things you need to keep in mind
- You have signed Google's CLA (for this google bot will help you after creating your first pr)
- Travis CI Build (tip: make sure to format all your dart files)
- Read `CONTRIBUTING.md` file

I hope this helps.

**Comment by tusharojha** [comment]
This issue can be closed now!
