### ISSUE TITLE
sample code for search bar animation

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/samples#553]
is any sample code for this Gif image?

![98mMw](https://user-images.githubusercontent.com/6617583/94159199-218f3300-fe90-11ea-8731-efc1815a24bb.gif)

that's like with Gmail search bar

**Comment by RedBrogdon** [comment]
It's not something we have a sample for here. I recognize that image from the Material motion package, though, which does include some samples: https://github.com/flutter/packages/tree/master/packages/animations
