### ISSUE TITLE
Why do I get an error on context.read<>();

### ISSUE THREAD

**Issue by duncangroenewald** [flutter/samples#558]
Is this an old or out of date sample ?

**Comment by RedBrogdon** [comment]
Without more information, it's difficult to understand the problem you ran into. Can you tell us:

* Which sample you were running?
* On what platform?
* What is the output of `flutter doctor -v` on your system?
* What were you doing in the app at the time the problem occurred?

**Comment by duncangroenewald** [comment]
It seems I needed to specify version 4.1.0 in dependencies section.  For some reason it was set to 3.0.0.

**Comment by RedBrogdon** [comment]
I'm still not quite sure which sample you mean, but I'm glad you found a solution to the issue. Thanks!

**Comment by Jackstraw007** [comment]
provider_shopper @RedBrogdon  this sample
