### ISSUE TITLE
[Animations] Add title property (AppBar) for All the Routes.

### ISSUE THREAD

**Issue by Raj-Dave368** [flutter/samples#564]
### Description

There is no title on some Route Page which can show, What type of Animation Page is Demonstrating.
![image](https://user-images.githubusercontent.com/54175432/96062870-5e10e600-0eb4-11eb-99c2-ad971c28941f.png)

* When I was testing the app I was Just clicking `ListTile`(main.dart) Randomly,

![image](https://user-images.githubusercontent.com/54175432/96061699-84815200-0eb1-11eb-8bc9-36fe68e11d5d.png)

* And I was navigating to Corresponding Page But After Navigating to the Screen  **I didn't know which type of Animation I am Trying** (Because: Page Doesn't Contain title On The `AppBar`).

![image](https://user-images.githubusercontent.com/54175432/96062339-0f168100-0eb3-11eb-9160-fa3a1d8ba2d4.png)

* Before Navigating to Any Page, I had to first Remember the `ListTile.title`. [a few pages have a title, but I'll like to have for all]

![image](https://user-images.githubusercontent.com/54175432/96062171-ad561700-0eb2-11eb-92c4-4a7658f5844b.png)

But I would Like to Make it More User Friendly and Easy to Use.
Something like this:

![image](https://user-images.githubusercontent.com/54175432/96062431-484ef100-0eb3-11eb-98f2-813ddb57fb27.png)

This is my first issue and I would like to Solve this Issue.

**Comment by Raj-Dave368** [comment]
@RedBrogdon @AyushBherwani1998 Please Review my issue, if the corresponding issue does not exist already, then I would like to Make a PR Because I have done this minor Changes, which have Huge Impact(80/20 principle).

Thanks,
                                                                                                                                                                         - Your new contributor.

**Comment by AyushBherwani1998** [comment]
Hey @Raj-Dave368, thanks for opening the issue. IMO, it will make the UX better. We still have to wait for Andrew's take on this. Till then, you can make changes in your system, and if this is something the samples need, you can submit a PR.

**Comment by RedBrogdon** [comment]
I agree, and I imagine @johnpryan would as well (though he's free to disagree with me 😄 ).

**Comment by Alabhya268** [comment]
@Raj-Dave368 are you still working on this issue? If not I would like to work on this issue.

**Comment by Alabhya268** [comment]
@RedBrogdon , I want to work on this issue could you please assign it to me ?

**Comment by adarsh-technocrat** [comment]
@Raj-Dave368   is this issue is closed?

**Comment by adarsh-technocrat** [comment]
Hello, @RedBrogdon  @AyushBherwani1998  I'm new to the open-source contribution and I really want to work on the issues and contribute to it can you please guide me from where I should start with or what is the right way to start. I found this issue in which I like to land my first PR if no one is working on it.

Thank you!

**Comment by Raj-Dave368** [comment]
Sorry for late reply, i had exam and still I am busy in some other work and cannot work on this issue.
@Alabhya268 you can work on this issue if you want.
Thank you

**Comment by Alabhya268** [comment]
> Sorry for late reply, i had exam and still I am busy in some other work and cannot work on this issue.
> @Alabhya268 you can work on this issue if you want.
> Thank you

Thanks@Raj-Dave368 , I'll soon open PR for this issue.

**Comment by Raj-Dave368** [comment]
Fine 
I m closing this PR.
Sorry @RedBrogdon

**Comment by RedBrogdon** [comment]
> Fine
> I m closing this PR.
> Sorry @RedBrogdon

That's okay. Good luck with your classwork!
