### ISSUE TITLE
[testing_app] We should add a placeholder for favorites list

### ISSUE THREAD

**Issue by tusharojha** [flutter/samples#578]
## Description
As the title clears the fact that when there is no item marked as favorites the list view of Favorites page shows a blank screen. In that case, we should add a placeholder specifying that there is **no item in the list**.

`Also, we can remove this debug banner from the top right.`
![Screenshot](https://user-images.githubusercontent.com/36601970/97772506-f32b0480-1b6d-11eb-9735-9f99d6ecddfa.jpeg)

**Comment by tusharojha** [comment]
@RedBrogdon 
If fixing this issue will be helpful to the sample, then I think we can add the _good first issue_ label to it.

**Comment by abd99** [comment]
Thanks for filing an issue @tusharojha!
This seems like a legitimate issue. If you want to fix this, then go ahead and create a PR. Otherwise, please mention so that others can contribute. =)

> Also, we can remove this debug banner from the top right.

I won't recommend doing this as the debug banner is there for a reason. It shows that the app is running in debug mode and will have features such as hot-reload enabled that are limited to debug mode. It automatically disappears when the app is run in release or profile mode.

**Comment by tusharojha** [comment]
> If you want to fix this, then go ahead and create a PR. Otherwise, please mention so that others can contribute. =)

I would love to land a PR for this issue.

> I won't recommend doing this as the debug banner is there for a reason. It shows that the app is running in debug mode and will have features such as hot-reload enabled that are limited to debug mode. It automatically disappears when the app is run in release or profile mode.

Yes, I agree but I pointed out this because other samples in the repository have disabled this banner.

**Comment by RedBrogdon** [comment]
Echoing what @abd99 mentioned, I would not remove the debug banner. While it may be disabled in some of the apps in this repo, it's not something we recommend doing unless there's a really good reason for it.

Providing a placeholder seems like a good idea, though. Be aware, though, that testing_app exists to teach people how to write good tests for Flutter applications. Consider the existing body of tests when you make this change: would any need to be updated? Would any new tests need to be added?

**Comment by tusharojha** [comment]
@RedBrogdon 
> Echoing what @abd99 mentioned, I would not remove the debug banner. While it may be disabled in some of the apps in this repo, it's not something we recommend doing unless there's a really good reason for it.

Got it 👍 

> would any need to be updated? Would any new tests need to be added?

I had run all the tests and are passing successfully. But I am facing issues in running just one test i.e. in the `e2e_test.dart` file. I don't think it is because of the change I made since I was not able to run it successfully on the master branch too. 

As a learner honestly, I don't have much experience with e2e tests. So, it would be a great help if you look into it or can help me with some tips on it.

**Comment by tusharojha** [comment]
Closing this issue as it is solved in #581.
