### ISSUE TITLE
[Veggie Seasons] We should add a save button on VeggieCard to directly save Veggies to Garden

### ISSUE THREAD

**Issue by Hardikkr** [flutter/samples#580]
**Description:**
This issue is focused on enhancing the "Veggie Seasons" app. We can add a save button in the Veggie Card so that a user can directly save a Veggie to the Garden. 

**Why this needs to be done?**
This will improve the UX as user don't have to open the card everytime in order to save a veggie in the garden.

**Implementation:**
This can be implemented in the "Search" section also.

**Example:**
![2020-11-01 (2)](https://user-images.githubusercontent.com/61787056/97801871-ce19bd00-1c65-11eb-82e0-dbac9d7ba24a.png)

Please review this issue @RedBrogdon @abd99 @AyushBherwani1998

**Comment by RedBrogdon** [comment]
An interesting idea.

The veggieseasons app has two goals, which you can see in its README:

* Show how to build an interface that iOS users will feel right at home with.
* Show how Flutter's Cupertino widgets work together.

While this change would certainly make it easier to mark a veggie as a favorite, would it further either of those goals (I'm not arguing against the change here -- I'm genuinely asking the question 😄 )? Is using an icon as pictured the best way to add a toggle to an info card? What other UX patterns do iOS apps use for this sort of thing? Have you considered any of them as alternatives? Is there a Cupertino widget that could be shown off instead?

**Comment by Hardikkr** [comment]
>  Is using an icon as pictured the best way to add a toggle to an info card?

This may not be the best way to mark veggie as favourite, but it is an easy and simple way to mark as favourite.

> would it further either of those goals

This change is not that much important as it is not satisfying any of the goals of veggieseasons app.
Thanks for reviewing this issue.
