### ISSUE TITLE
[feature_request] State management examples

### ISSUE THREAD

**Issue by cazci** [flutter/samples#585]
Since there are several state management approaches like Provider, Redux, BLoC, and MobX in practice, I think it would be better to add some sample implementations here for beginners. This would help them to quickly capture the usages and differences which will help with their learning curve. 

While going through the repo I found that **Provider Shopper** app already demonstrates the provider pattern clearly. So I guess a similar approach can be used for others as well. Thanks :)

**Comment by emem365** [comment]
@cazci
Have you had a look at [Brian Egan's architecture samples](https://github.com/brianegan/flutter_architecture_samples). Its a nice collection for what I would say are almost all of the architectures in practice for flutter. I might be wrong but they are a lot.

**Comment by cazci** [comment]
@emem365 thanks for the info, I went through it and it's a pretty good one. I'll just close this issue for now :)
