### ISSUE TITLE
experimental/desktop_photo_search doesn't handle utf8 correctly.

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#586]
@mit-mit who should I chat to about `built_value` and decoding utf8 data correctly? I'm guessing I need to use [`characters`](https://pub.dev/packages/characters) with `built_value` somehow?

**Comment by mit-mit** [comment]
cc @davidmorgan @lrhn

**Comment by davidmorgan** [comment]
Could you give a bit more info on the issue you're seeing, please?

**Comment by domesticmouse** [comment]
30,000' explanation is that I'm incorrectly rendering search requests that contain non-latin1 characters:

<img width="806" alt="Screen Shot 2020-11-07 at 11 42 38 am" src="https://user-images.githubusercontent.com/30503/98426785-5973d200-20ee-11eb-9634-9fdd0a054d4c.png">

In digging into the problem (see https://github.com/flutter/samples/pull/587/files) I figured out a couple of things. First, our `http` package will default to decoding an `application/json` stream with the latin1 parser. Unfortunately for me, Unsplash API is returning API results using UTF8 without declaring it as such.

**Comment by davidmorgan** [comment]
Thanks--indeed, looks like the issue is outside `built_value`.

**Comment by lrhn** [comment]
And outside `characters` too. You'll have to set the encoding on the HTTP request manually.
```dart
import "package:http/http.dart";
...
  var response = await get(uri);
  var data = utf8.fuse(json).decode(response.bodyBytes);
```
(Do use the `http` package for HTTP requests, because using `dart:io` is not compatible with Flutter-for-Web).

**Comment by domesticmouse** [comment]
With the above integrated in https://github.com/flutter/samples/pull/590/commits/8e0f5c441fc2d4eaf7b3b4526c424336f6bd0202, it still trips up on the following on macOS (but renders fine in Chrome).

```json
      "user": {
        "id": "JzhDKu_NfNs",
        "updated_at": "2020-11-08T00:33:05-05:00",
        "username": "arusfly",
        "name": "Arusfly 🌿",
        "first_name": "Arusfly 🌿",
        "last_name": null,
        "twitter_username": "arusfly",
        "portfolio_url": "http://www.instagram.com/vallartadiarios",
        "bio": null,
        "location": "Puerto Vallarta",
        "links": {
          "self": "https://api.unsplash.com/users/arusfly",
          "html": "https://unsplash.com/@arusfly",
          "photos": "https://api.unsplash.com/users/arusfly/photos",
          "likes": "https://api.unsplash.com/users/arusfly/likes",
          "portfolio": "https://api.unsplash.com/users/arusfly/portfolio",
          "following": "https://api.unsplash.com/users/arusfly/following",
          "followers": "https://api.unsplash.com/users/arusfly/followers"
        },
        "profile_image": {
          "small": "https://images.unsplash.com/profile-1588638936205-9c639973f359image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32",
          "medium": "https://images.unsplash.com/profile-1588638936205-9c639973f359image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64",
          "large": "https://images.unsplash.com/profile-1588638936205-9c639973f359image?ixlib=rb-1.2.1&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128"
        },
        "instagram_username": "vallartadiarios ",
        "total_collections": 0,
        "total_likes": 61,
        "total_photos": 33,
        "accepted_tos": true
      },
```

<img width="842" alt="Screen Shot 2020-11-10 at 4 48 45 pm" src="https://user-images.githubusercontent.com/30503/98632983-ac5ebb00-2374-11eb-8934-28295decfe8b.png">
