### ISSUE TITLE
[testing_app] Migrate to integration_test package

### ISSUE THREAD

**Issue by abd99** [flutter/samples#622]
It has been a few days since the [`integration_test`](https://pub.dev/packages/integration_test) package was released and we should probably migrate the sample to use it.

The [`e2e`](https://pub.dev/packages/e2e) package has also been deprecated and it's recommended to use the new package instead.

So, should we just remove the existing `e2e` and `flutter_driver` tests and replace them with the new tests as the developers writing new tests should be using the new package anyway or should we keep them for a while before we remove them?

WDYT @domesticmouse @RedBrogdon?

/cc @CareF

**Comment by domesticmouse** [comment]
@johnpryan probably has some input here 😉

**Comment by johnpryan** [comment]
+1 - @abd99 would you like to work on it?

Here are the relevant docs + blog posts:

- [flutter.dev/docs/testing/integration-tests](https://flutter.dev/docs/testing/integration-tests)
- [Updates on flutter testing](https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e)

One small thing this sample should do is use the structure that is created when you run `flutter create`. (This is not currently what the integration testing docs recommend):

```
integration_test/
  app_test.dart
  driver.dart
```

**Comment by RedBrogdon** [comment]
Just a heads up: I moved the repo from Travis CI to GitHub Actions today. I haven't had a chance to add back the encrypted credentials used for our Firebase Test Lab runs. That will likely need to wait until next year.

I don't believe that should block any work done for this, but I wanted to make sure y'all knew.

**Comment by CareF** [comment]
I probably don't have time for doing the migration but feel free to include me if there's anything I need to explain about the e2e tests in the sample.

**Comment by abd99** [comment]
Yes @johnpryan, I'm trying my best to keep the sample updated. Thanks for the instructions!

**Comment by abd99** [comment]
> I probably don't have time for doing the migration but feel free to include me if there's anything I need to explain about the e2e tests in the sample.

Don't worry about that @CareF, I'll be the one doing the migration. I just wanted to know if you have anything to say in this discussion as you were the one who added the e2e tests in the sample.
