### ISSUE TITLE
Headers missing in code in  Place Tracker Files

### ISSUE THREAD

**Issue by arteevraina** [flutter/samples#649]
As mentioned in [guidelines](https://github.com/flutter/samples/blob/master/CONTRIBUTING.md) that all files in the project must start with the following header.

```
// Copyright 2020 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
```

This is missing in [place_tracker](https://github.com/flutter/samples/tree/master/place_tracker) sample app. If this is not done on some specific purpose. I would like to fix this up.

WDYT @RedBrogdon @domesticmouse ?

**Comment by ditman** [comment]
> If this is not done on some specific purpose. I would like to fix this up.

Yeeet! No, these were probably forgotten by mistake. (there might be other apps in the repo with the same issue).

@arteevraina if you want to contribute a patch, it'll be very welcome, for sure!

**Comment by johnpryan** [comment]
That would be great. We might want to also add some [tooling](https://pub.dev/packages/copywriter) to check this too.

**Comment by arteevraina** [comment]
> > If this is not done on some specific purpose. I would like to fix this up.
> 
> Yeeet! No, these were probably forgotten by mistake. (there might be other apps in the repo with the same issue).
> 
> @arteevraina if you want to contribute a patch, it'll be very welcome, for sure!

Yes, sure thing. I will make a PR for this. After rechecking I found out that this header was missing in the files of the following repos- 
* [web](https://github.com/flutter/samples/tree/master/web).
* [platform-design](https://github.com/flutter/samples/tree/master/platform_design).
* [platform-channel](https://github.com/flutter/samples/tree/master/platform_channels).
* [ios_app_clip (only one file)](https://github.com/flutter/samples/blob/master/ios_app_clip/test/widget_test.dart).

**Comment by arteevraina** [comment]
> That would be great. We might want to also add some [tooling](https://pub.dev/packages/copywriter) to check this using GH Actions.

Yes, I am always open to contributing to the community.

**Comment by arteevraina** [comment]
> That would be great. We might want to also add some [tooling](https://pub.dev/packages/copywriter) to check this using GH Actions.

Can I create a separate issue for this and start working on it?

**Comment by ditman** [comment]
> Can I create a separate issue for this and start working on it?

Yes, that'd be the best way to go about it. That way we can close this issue with the PR you sent fixing headers, without waiting for the tooling fix :)
