### ISSUE TITLE
A new folder for Caching related projects

### ISSUE THREAD

**Issue by iresharma** [flutter/samples#650]
During my recent project I explored a lot of Caching options/alternatives different libraries to tap into the SQLlite database or a noSQL db caching using the HiveDb dependency

**Comment by RedBrogdon** [comment]
Thanks for the feature request, @iresharma. This repo is mostly focused on samples that relate to the SDK itself rather than specific packages -- even well-used ones like the two you listed.

That said, you mentioned exploring caching options in a recent project. Did you create any sample code as a result? If so, I'd be happy to help bring it to the attention of the Flutter dev community.

**Comment by iresharma** [comment]
> Thanks for the feature request, @iresharma. This repo is mostly focused on samples that relate to the SDK itself rather than specific packages -- even well-used ones like the two you listed.
> 
> That said, you mentioned exploring caching options in a recent project. Did you create any sample code as a result? If so, I'd be happy to help bring it to the attention of the Flutter dev community.

Sample code no, but caching seems like a very important aspect of building a mobile app to provide offline content as well. 

As you said this repository is mostly for flutter core features, It would be a great idea to create a repo to demonstrate some important aspects like caching.

What say ?

**Comment by RedBrogdon** [comment]
> As you said this repository is mostly for flutter core features, It would be a great idea to create a repo to demonstrate some important aspects like caching.

I think creating a dedicated repo for samples related to caching would be a great idea. It's not something the Flutter DevRel team has engineering bandwidth for right now, but if it's a project you decide to take on, I'm sure the community would appreciate it. 

You can spread the word about that or any of your other projects via indices like:

* [It's all Widgets](https://itsallwidgets.com)
* [Awesome Flutter](https://github.com/Solido/awesome-flutter)
