### ISSUE TITLE
Update flutter_maps_firestore for upcoming release

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#652]
From [failed CI run (beta channel)](https://github.com/flutter/samples/pull/651/checks?check_run_id=1718813742#step:5:341):

```
== Testing 'flutter_maps_firestore' on Flutter's  channel ==
~/work/samples/samples/flutter_maps_firestore ~/work/samples/samples
Running "flutter pub get" in flutter_maps_firestore...           1,892ms
Analyzing flutter_maps_firestore...                             

   info • 'PluginRegistry' is deprecated and shouldn't be used. Use Registrar instead. This feature was deprecated after v1.24.0-7.0.pre. • lib/generated_plugin_registrant.dart:12:22 • deprecated_member_use
   info • 'registrarFor' is deprecated and shouldn't be used. This method is redundant. It returns the object on which it is called. This feature was deprecated after v1.24.0-7.0.pre. • lib/generated_plugin_registrant.dart:13:41 • deprecated_member_use
```

**Comment by RedBrogdon** [comment]
I've brought the beta branch up to date so this can be landed there.

**Comment by domesticmouse** [comment]
Cool, thanks @RedBrogdon

**Comment by AyushBherwani1998** [comment]
@domesticmouse Since we are already updating the sample, I think we should also bump up the cloud_firestore package and included the other firebase_core dependency too.

**Comment by domesticmouse** [comment]
Please do 😎

**Comment by AyushBherwani1998** [comment]
@RedBrogdon @domesticmouse I have a question. Why do we have generated_plugin_registrant? We don't support web for this sample, and I believe it should be git ignored.

**Comment by domesticmouse** [comment]
Adding web support for this sample should be on the task list
