### ISSUE TITLE
Update provider_shopper for upcoming release

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#657]
From [failing CI run](https://github.com/flutter/samples/pull/651/checks?check_run_id=1718979450#step:5:538):

```
== Testing 'provider_shopper' on Flutter's beta channel ==
~/work/samples/samples/provider_shopper ~/work/samples/samples
Running "flutter pub get" in provider_shopper...                   885ms
Analyzing provider_shopper...                                   

   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/cart.dart:88:38 • deprecated_member_use
```

**Comment by Adityabhaumik** [comment]
Hello I would like to work on this , could someone please clarify what exactly needs to be done

**Comment by Adityabhaumik** [comment]
3 checks are failing is there anything I could do to fix them  @domesticmouse . 
1->Flutter CI / Test Flutter stable on ubuntu-latest (pull_request)
2->Flutter CI / Test Flutter stable on macos-latest (pull_request) 
3->Flutter CI / Test Flutter stable on windows-latest (pull_request)

**Comment by domesticmouse** [comment]
Those three checks are expected to fail until beta becomes the next stable. You can ignore them for the time being. 😎

**Comment by RedBrogdon** [comment]
I've brought the beta branch up to date so this can be landed there.

**Comment by adarsh-technocrat** [comment]
Hello @domesticmouse as related PR has been to merge to the beta branch we can close this issue :)

**Comment by domesticmouse** [comment]
Thanks @adarsh-technocrat 😎
