### ISSUE TITLE
Add Google and Unsplash terms links to experimental/desktop_photo_search

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#667]
Add links to the following in an about dialog or similar:

- https://policies.google.com/terms
- https://unsplash.com/terms

**Comment by SatYu26** [comment]
@domesticmouse  hello sir. I was working on this issue and thought that is it good if we add these links in about section  in menubar?

**Comment by SatYu26** [comment]
@domesticmouse Hello sir. I have made few changes according to the requirement in this issue. 
As of now the dialog looks like this:
![About_Dialog](https://user-images.githubusercontent.com/41650056/106025703-0444cc80-60ef-11eb-8bec-3d4e9d816069.png)

I have added sentences according to the information available to me but if you let me know the specific details of the statements i will make those changes quickly.

Also i have added the access point for this dialog in About menu inside the menubar, As you can see in this picture.
![InkedHomeScreen_LI](https://user-images.githubusercontent.com/41650056/106026175-803f1480-60ef-11eb-9e12-d907f1e64830.jpg)

I will can make more changes also if required by you.
