### ISSUE TITLE
web_dashboard demo doesn't work. "Sign in with Google" buttons does nothing

### ISSUE THREAD

**Issue by jlubeck** [flutter/samples#676]
I wanted to try out the web_dashboard demo on https://flutter.github.io/samples/web/web_dashboard/#/ and when I click on the button "Sign in with Google" nothing happens.

**Comment by tusharojha** [comment]
Hi @jlubeck!

Have you followed all the steps mentioned in the [README](https://github.com/flutter/samples/blob/master/experimental/web_dashboard/README.md) file about creating a new firebase project and enabling Google Sign-In for your project? If not, I would recommend you to go through all steps and try again.

**Comment by jlubeck** [comment]
@tusharojha I did not do anything, I just went to https://flutter.github.io/samples which was mentioned in the Readme file, and clicked on the Dashboard example (https://flutter.github.io/samples/web_dashboard.html). In there I clicked on `Launch App` which I would expect to work without me having to do anything (since it doesn't say anywhere in that samples page that I need to do anything)

**Comment by tusharojha** [comment]
@jlubeck 
Actually, in my case it takes me to the home tab of dashboard app.

**Comment by jlubeck** [comment]
Did you try it in an Incognito window? It just stays there for me, and this error is thrown in the console:

```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://flutter.github.io/') with script ('https://flutter.github.io/flutter_service_worker.js'): A bad HTTP response code (404) was received when fetching the script.
```

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @jlubeck. I'm not able to replicate your experience, at least not in my own copy of Chrome:

![image](https://user-images.githubusercontent.com/969662/105953210-a4cfb980-6027-11eb-81d6-8d4e970e73ab.png)

Can you tell me if you see any failing network requests in the Chrome Inspector's network tab, or any additional errors in your console?

**Comment by jlubeck** [comment]
While recording a screencast, it finally opened after like the 5th click. I wonder if it is running into this issue https://github.com/flutter/flutter/issues/70529?

That is fixed in master, but maybe these examples were compiled with an older version?

**Comment by jlubeck** [comment]
Yes, that's it... after I got in, I also ran into the same issue with every button in the demo... I have to click a lot of times for anything to work. So not sure if this can be closed, or the demos need to be compiled with a more recent version of flutter so this is fixed?

**Comment by RedBrogdon** [comment]
Interesting. Do you see the issue in Chrome, but not Safari? And, just to verify, are you running Big Sur?

**Comment by jlubeck** [comment]
I am using Big Sur yes, and I ran into the same issue on one of my own projects myself a couple months ago, that's why I knew about that issue. But looks like everything is working fine on both browsers now. Did the demos get rebuilt by any chance? Or just voodoo on my computer? I'll close this now since it is no longer an issue, but do let me know please!

**Comment by RedBrogdon** [comment]
Updated builds of the apps were recently deployed as part of a fix to the visual samples index (flutter.github.io/samples). 😄
