### ISSUE TITLE
Launch App Button on click is not enabled completely

### ISSUE THREAD

**Issue by SatYu26** [flutter/samples#684]
in all of the sample web apps in [https://flutter.github.io/samples/#](https://flutter.github.io/samples/#) , the launch app button is not working completely. 
In the portion circled with red is not working, i.e. if you click on it button wont respond.

![InkedScreenshot 2021-01-28 161124_LI](https://user-images.githubusercontent.com/41650056/106127738-ce522780-6184-11eb-8ec9-26872a72d38b.jpg)

**Comment by cazci** [comment]
hi @SatYu26, thank you for noticing this and the issue with the source code button (#683). Since these two and #690 are related, I'll fix them all with a single patch

**Comment by SatYu26** [comment]
@cazci That would be great. if you would like help, I would also love to contribute in it.
Do let me know!!

**Comment by cazci** [comment]
Happy to see your enthusiasm @SatYu26. However, #691 will fix these issues for now and close them on merge. Please keep contributing :)

**Comment by SatYu26** [comment]
@cazci That's great. Thank you!!
