### ISSUE TITLE
The home page image for Unit Testing cookbook is not updated

### ISSUE THREAD

**Issue by SatYu26** [flutter/samples#686]
The home page image for unit testing cookbook i.e. [https://flutter.github.io/samples/an_introduction_to_unit_testing.html](https://flutter.github.io/samples/an_introduction_to_unit_testing.html) is not updated to latest.

**Comment by tusharojha** [comment]
Hi @SatYu26 

Check out this related issue #394.
Rather than updating all the images manually the idea is to modify the scraper to do it.

@johnpryan can give more info on it.

**Comment by SatYu26** [comment]
that would be great!!
