### ISSUE TITLE
In majority of samples (of visual sample index) only the last tag is clickable and functioning.

### ISSUE THREAD

**Issue by utkarshshendge** [flutter/samples#690]
![mask](https://user-images.githubusercontent.com/57677520/106157360-a4aaf780-61a8-11eb-815f-bc343882a66e.png)
## Here only the highlighted tag is clickable .

While in [platform_view_swift](https://flutter.github.io/samples/platform_view_swift.html) and [platform_design](https://flutter.github.io/samples/platform_design.html) the last 2 tags are clickable.

**Comment by RedBrogdon** [comment]
Verified. It looks like the addition of the carousel came with a clear DIV element `slider-container`, which overlays the tags (and parts of the buttons) and is absorbing mouse events.

**Comment by RedBrogdon** [comment]
CC @johnpryan, @cazci.

**Comment by cazci** [comment]
@utkarshshendge thank you for raising this issue

@RedBrogdon I'll work on this and open a PR. It seems like there are another two issues associated (#683, #684), and I'll fix them as well

**Comment by utkarshshendge** [comment]
@cazci  Great!!
If you need any help fixing the bug please let me know. I will be more than happy to contribute.

**Comment by cazci** [comment]
Thank you for asking @utkarshshendge. However, I've already fixed this with #691. Please keep it up and continue contributing, cheers! :)
