### ISSUE TITLE
[web/particle_background] One of the links in readme does not work.

### ISSUE THREAD

**Issue by utkarshshendge** [flutter/samples#708]
In [README.md](https://github.com/flutter/samples/blob/master/web/particle_background/README.md) of [particle_background](https://github.com/flutter/samples/tree/master/web/particle_background) example ,the link  [published here](https://github.com/felixblaschke/simple_animations_example_app) gives error 404.

**Comment by RedBrogdon** [comment]
Fired by #709.

**Comment by RedBrogdon** [comment]
Nice catch!
