### ISSUE TITLE
Migrate infinite_list to null-safety

### ISSUE THREAD

**Issue by abd99** [flutter/samples#715]
I'm migrating the infinite_list sample to null-safety. Hopefully, no one else was working on this before.
I'm creating my branch from the current beta branch. Let me know if there's something I should look out for.

/cc @domesticmouse @filiph

**Comment by johnpryan** [comment]
I think @filiph is the assignee for this right now

**Comment by filiph** [comment]
On it!

**Comment by filiph** [comment]
Oh wait, @abd99. If you're already in the process, just let me know. Happy to review a PR!

**Comment by abd99** [comment]
@filiph, I have created PR #716. I think you missed that because of similar names.

**Comment by arteevraina** [comment]
Hey @abd99 @filiph ! Can I help to migrate the other samples present in the repo to null safety? It would be a great learning experience for me :)

**Comment by domesticmouse** [comment]
Hey @arteevraina,

Thanks for the offer of help, it is much appreciated! Please check with @RedBrogdon as I believe a some of the samples have already been migrated on the https://github.com/flutter/samples/tree/beta branch.

**Comment by arteevraina** [comment]
> Hey @arteevraina,
> 
> Thanks for the offer of help, it is much appreciated! Please check with @RedBrogdon as I believe a some of the samples have already been migrated on the https://github.com/flutter/samples/tree/beta branch.

Sure thing 👍

**Comment by abd99** [comment]
That'd be great @arteevraina, 

Adding to what @domesticmouse said, be sure to create an issue if you pick any sample so that there's no duplication of work.

**Comment by RedBrogdon** [comment]
Closing this, since the infinite_list app has been migrated and @arteevraina has taken on provider_counter.
