### ISSUE TITLE
Migrate provider_counter app to null safety

### ISSUE THREAD

**Issue by arteevraina** [flutter/samples#720]
I am working to migrate `provider_counter` to null safety. I think this would help me a good start to help migrate other samples to null safety as well.

@domesticmouse @RedBrogdon Can you please confirm that this app is not already migrated to null safety ?

**Comment by adarsh-technocrat** [comment]
Hey, @arteevraina  great start  `provider_counter` app is not yet migrated to null safety,  if you want to see that samples are migrated to null safety or not then check the `beta` branch :)

cc: @domesticmouse  @RedBrogdon  will guide you better to proceed.

**Comment by arteevraina** [comment]
Sure thing @adarsh-technocrat :)

**Comment by filiph** [comment]
Hi @arteevraina. Thanks for offering to help. Please take a stab at it. We're trying to get these to the `beta` branch soon, so your help is very appreciated. 

@ me on the PR so I can review. Cheers!
