### ISSUE TITLE
[provider_counter] Migrate to null safety

### ISSUE THREAD

**Issue by filiph** [flutter/samples#728]
The sample at https://github.com/flutter/samples/tree/master/provider_counter needs to be migrated to sound null safety. I'm going to do it by Wednesday EOD unless someone else wants to take a stab at it soon. If so, please send a PR against the `beta` branch ([example](https://github.com/flutter/samples/pull/716)).

**Comment by filiph** [comment]
(Possible to combine with #729.)

**Comment by abd99** [comment]
I'm on it.

**Comment by arteevraina** [comment]
Hello @abd99 :) I was working on this with ref to #720 and I have already sent a PR for this #734 .

**Comment by abd99** [comment]
No worries. I forgot about that. Great work!

**Comment by arteevraina** [comment]
Thanks @abd99 :)

**Comment by RedBrogdon** [comment]
Closed by #734.
