### ISSUE TITLE
[provider_shopper] Migrate to null safety

### ISSUE THREAD

**Issue by filiph** [flutter/samples#729]
The sample at https://github.com/flutter/samples/tree/master/provider_shopper needs to be migrated to sound null safety. I'm going to do it by Wednesday EOD unless someone else wants to take a stab at it soon. If so, please send a PR against the `beta` branch ([example](https://github.com/flutter/samples/pull/716)).

**Comment by filiph** [comment]
(Possible to combine with #728.)

**Comment by arteevraina** [comment]
@filiph I will send a patch for this by today.

**Comment by arteevraina** [comment]
Hey @filiph , I will migrate this one by today.

**Comment by arteevraina** [comment]
Since `provider_shopper` has been already migrated to null safety. I think this can be closed now. WDYT @filiph ?
