### ISSUE TITLE
[testing_app] Migrate to null-safety

### ISSUE THREAD

**Issue by abd99** [flutter/samples#731]
The `integration_test` package was moved to the `flutter/flutter` repo a few months back. However, its version on the beta channel doesn't have null-safety implemented.
```
➜  testing_app git:(testing_app_null_safety) ✗ dart pub outdated --mode=null-safety
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name      Current  Upgradable  Resolvable           Latest               

direct dependencies:
cupertino_icons   ✗1.0.0   ✓1.0.2      ✓1.0.2               ✓1.0.2               
provider          ✗4.3.3   ✗4.3.3      ✓5.0.0-nullsafety.5  ✓5.0.0-nullsafety.5  

dev_dependencies:
integration_test  ✗(sdk)   ✗(sdk)      ✗(sdk)               ✗(sdk)               

1 upgradable dependency is locked (in pubspec.lock) to an older version.
To update it, use `dart pub upgrade`.

1 dependency is constrained to a version that is older than a resolvable version.
To update it, edit pubspec.yaml, or run `dart pub upgrade --null-safety`.
```

Creating this issue as a reminder to migrate the testing sample once the integration_test package is null-safe on the stable/beta channels.

**Comment by Swayam221** [comment]
Can I be guided to work on this?

**Comment by abd99** [comment]
Hello @Swayam221,

Thanks for showing interest in contributing to the repo.

As mentioned in the issue description, there's a dependency for this sample that isn't migrated yet. We'll have to wait for it migrate first. Then, we can migrate this sample.
