### ISSUE TITLE
NDK missing error in flutter/samples CI

### ISSUE THREAD

**Issue by gaaclarke** [flutter/samples#737]
An unrelated PR started showing an error in the samples CI:  https://github.com/flutter/samples/pull/677/checks?check_run_id=1923183048

`No version of NDK matched the requested version 21.3.6528147.`

It sounds related to https://github.com/flutter/flutter/issues/53657.

**Comment by jmagman** [comment]
PR to upgrade that version to the one available on CI: https://github.com/flutter/samples/pull/738.  I'm not sure what a more permanent solution would be since this seems to be a moving target.
