### ISSUE TITLE
Camera | package video_player not found

### ISSUE THREAD

**Issue by abelardolg** [flutter/samples#746]
Hi,

When I pasted the code of https://pub.dev/packages/camera into my app and I run it, Flutter showed this message:
![image](https://user-images.githubusercontent.com/22522883/109501012-4c149600-7a97-11eb-904c-1df5aaf07feb.png)

The above example is incomplete since this package is not found.

Best regards.

**Comment by arteevraina** [comment]
@abelardolg I think you need to run `flutter pub get ` after adding the dependency to your `pubspec.yaml`.

**Comment by utkarshshendge** [comment]
Hi @abelardolg , the example contains  [video_player](https://pub.dev/packages/video_player) plugin . Please install it before running the example.

**Comment by abelardolg** [comment]
Ok, it was installed. 

To my mind, it should be mentioned under "installation" section.

Best regards.
