### ISSUE TITLE
Moving veggieseasons out of experimental 

### ISSUE THREAD

**Issue by tusharojha** [flutter/samples#749]
## Description

Samples like `web_dashboard` & `veggieseasons` can now work on stable channels thanks to Flutter 2. I think we can move these samples out of the `experimental` directory to showcase the web & state restoration features.

@johnpryan @domesticmouse let me know if this seems the right time to do it.

**Comment by domesticmouse** [comment]
I'm supportive of moving `veggieseasons`. I'll leave it to @johnpryan to answer for `web_dashboard`. I'd suggest doing them as individual PRs in case John wants to delay moving the dashboard.

**Comment by johnpryan** [comment]
Created https://github.com/flutter/samples/issues/753 for web_dashbaord
