### ISSUE TITLE
The memory is still increased by 32M（not ～180K ，when new  FlutterViewController）

### ISSUE THREAD

**Issue by fengnudexiaoniao** [flutter/samples#751]
each additional Flutter instance in new FlutterViewController  beyond the first instance ，
The memory is still increased by 32m, not ～180K，Did you really test it? Do you provide any supporting data

**Comment by fengnudexiaoniao** [comment]
Each additional flutter instance in already exists  Flutterviewcontroller is ~ 180K in ios（ not new FlutterViewController ）

**Comment by domesticmouse** [comment]
Are you following the steps outlined in https://flutter.dev/docs/development/add-to-app/multiple-flutters?

**Comment by zhouxin1233** [comment]
> Are you following the steps outlined in https://flutter.dev/docs/development/add-to-app/multiple-flutters?

multiple_flutters_android not found

**Comment by fengnudexiaoniao** [comment]
> outlined

yes，I have tested the Multiple Flutter demo  in https://flutter.dev/docs/development/add-to-app/multiple-flutters

additional Flutter instance ，The memory is still increased by 32M （when in new FlutterViewController）

**Comment by zerozeus** [comment]
![image](https://user-images.githubusercontent.com/13057840/110450433-270acd80-80fe-11eb-83b0-f28cf19dd07f.png)
only release version is fully optimized
