### ISSUE TITLE
Move web_dashboard out of experimental

### ISSUE THREAD

**Issue by johnpryan** [flutter/samples#753]

**Comment by arteevraina** [comment]
Hey @johnpryan! If you have not started working on this one? Can I send a patch for this one?

**Comment by johnpryan** [comment]
Maybe, I need to check if this conflicts with any null safety work that's happening.

**Comment by arteevraina** [comment]
@johnpryan No worries.

**Comment by johnpryan** [comment]
Here's the issue to track the null safety upgrade: https://github.com/flutter/samples/issues/798 which depends on charts_flutter and charts_common upgrading to null safety: https://github.com/flutter/samples/issues/798 and google/charts#579
