### ISSUE TITLE
[testing_app] Adding snapshot tests

### ISSUE THREAD

**Issue by utkarshshendge** [flutter/samples#758]
## I think we should add a sample to demonstrate golden tests(snapshot tests).
The  existing  [testing_app](https://github.com/flutter/samples/tree/master/testing_app) is also a good example to demonstrate golden tests. I have added golden test to testing_app, and can be found in [this](https://github.com/utkarshshendge/samples/tree/master/testing_app/test) forked repo.  These tests are directly based upon widget tests .
I created 2 separate  files for favorites.dart and home.dart . Alternatively, I could have added them in the same file of widget tests( favorites_test.dart and home_test.dart). 

@RedBrogdon Please tell me if there are some suggestion on this,  and also whether should  I proceed with a PR?
As far as testing_app's [Readme](https://github.com/flutter/samples/blob/master/testing_app/README.md) is concerned , I will make necessary changes once the PR is merged.

**Comment by abd99** [comment]
Welcome to the repo, @utkarshshendge!

Coincidentally, I was also thinking the same thing last night while thinking of ways to improve the sample. I think we'll be good to go on this once we get a green signal from @RedBrogdon or @domesticmouse.

> I created 2 separate files for favorites.dart and home.dart . Alternatively, I could have added them in the same file of widget tests( favorites_test.dart and home_test.dart).

Keeping them separate is better in my opinion. It'll help in keeping the sample easy to navigate through and simple, which we always try to do throughout the repo.

> As far as testing_app's Readme is concerned , I will make necessary changes once the PR is merged.

You can add those changes to the PR itself.

I will provide more suggestions directly to the PR, if any.

**Comment by utkarshshendge** [comment]
Hi @domesticmouse , I would appreciate hearing your opinion on this.
