### ISSUE TITLE
How to access web samples in other server

### ISSUE THREAD

**Issue by yylittlefish** [flutter/samples#770]
Hi,
I'm using "flutter run -d web-server" to run the samples and it could run by accessing "http://localhost:34763" in local browser
but when I try to access it in another PC's borwser using "http://109.123.100.45:34763",
it can't be accessed.
is there any method to make it accessible in another PC?
thank you!

**Comment by domesticmouse** [comment]
Yeah, localhost is only available on the local host. One way around this is to build it, and then use a web server to serve the built webapp:

```
$ flutter build web
$ flutter pub global activate dhttpd
$ flutter pub global run dhttpd --path build/web --host 0.0.0.0
```
