### ISSUE TITLE
[form_app] Migrate to Null Safety

### ISSUE THREAD

**Issue by arteevraina** [flutter/samples#771]
Form App is currently not null safe. Most of the packages it depends on are null safe except for two dev-dependencies [`build_runner`](https://pub.dev/packages/build_runner) and [`json_serializable`](https://pub.dev/packages/json_serializable). So, whenever the null safe versions of packages are published. I would love to migrate `form_app `to null safety.

**Comment by tusharojha** [comment]
Hi @arteevraina!
These packages are null safe now. Would you like to migrate it?

**Comment by arteevraina** [comment]
Hi @tusharojha ! My health is not well these days. You can take upr this issue if you want 🙏

**Comment by tusharojha** [comment]
No problem! Take care 👍

**Comment by arteevraina** [comment]
Hi @tusharojha ! Are you still on this issue? If not, I would like to proceed with this.

**Comment by tusharojha** [comment]
You can take this.

**Comment by johnpryan** [comment]
@arteevraina you can migrate the app without waiting for build_runner and json_serializable to migrate, since they are dev dependencies.

**Comment by RedBrogdon** [comment]
This has been completed.
