### ISSUE TITLE
 multiple_flutters_android  Binding is not Undefined

### ISSUE THREAD

**Issue by au-top** [flutter/samples#786]
In multiple_ flutters_ In Android
settings.gradle 
setBinding(new Binding([gradle: this]))   ,Binding 
Undefined In multiple_ flutters_ In Android

```
include ':app'
rootProject.name = "Multiple Flutters"
setBinding(new Binding([gradle: this]))                                // new
evaluate(new File(                                                     // new
        settingsDir.parentFile,                                              // new
        './multiple_flutters_module/.android/include_flutter.groovy'                         // new
))
```

**Comment by au-top** [comment]
build error info 
```
Settings file 'D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_android\settings.gradle' line: 4

A problem occurred evaluating settings 'Multiple Flutters'.
> D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_module\.android\include_flutter.groovy (D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_module\.android\include_flutter.groovy)


```

**Comment by zhouxin1233** [comment]
> build error info
> 
> ```
> Settings file 'D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_android\settings.gradle' line: 4
> 
> A problem occurred evaluating settings 'Multiple Flutters'.
> > D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_module\.android\include_flutter.groovy (D:\project\flutterProject\samples-master\add_to_app\multiple_flutters\multiple_flutters_module\.android\include_flutter.groovy)
> ```

要先跑一遍multiple_flutters_module工程啊，胸得！

**Comment by au-top** [comment]
谢谢
