### ISSUE TITLE
Slow rendering in Flutter View Integration

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [flutter/samples#795]
Running https://github.com/flutter/samples/tree/master/add_to_app/android_view in Nexus 4 with Android 5.1.1 is possible
to see some dark edges while the user scrolls over the list.
Please take a look at this video:
https://user-images.githubusercontent.com/4115957/117561978-49d04880-b093-11eb-8dae-7cc7bee5ac36.mp4

![Screenshot 2021-05-09 at 06 57 33](https://user-images.githubusercontent.com/4115957/117562059-f27ea800-b093-11eb-981a-5a6a644bfe40.png)

**Comment by ericwindmill** [comment]
I'm closing this because 1) add-to-app is going to get major updates and 2) This issue is 3 years old.
