### ISSUE TITLE
Upgrade Gradle Tools to >= 4.1.2 + Gradle Wrapper >= 6.5.1 (Linux issue)

### ISSUE THREAD

**Issue by Gustl22** [flutter/samples#805]
Plz upgrade the gradle version of the projects in order to work properly on all platforms:
```
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi
```
Related:
https://github.com/flutter/flutter/issues/53657#issuecomment-795808016

build.gradle:
```
dependencies {
    classpath 'com.android.tools.build:gradle:4.1.3'
}
```

gradle-wrapper.properties:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

**Comment by domesticmouse** [comment]
Which sample is this for?

**Comment by Gustl22** [comment]
I suspect this affects all samples with these specs:
https://github.com/search?q=repo%3Aflutter%2Fsamples%20services.gradle.org%2Fdistributions%2Fgradle&type=code

https://github.com/search?q=repo%3Aflutter%2Fsamples+%22com.android.tools.build%3Agradle%22&type=code

But I think I originally tested it with the `platform_channel` sample, where the according versions have been updated in #1022
