### ISSUE TITLE
problems building `web/samples_index`

### ISSUE THREAD

**Issue by ghost** [flutter/samples#806]
not sure  if anyone tried to build it manually on latest dart (following the readme instructions), but
as per https://dart.dev/tools/pub/cmd
> the standalone pub command is deprecated

so even after installing via `flutter pub global activate grinder`, executing `grind generate`
results in `grind: 7: pub: not found`

related: https://github.com/google/grinder.dart/issues/381 (includes OS, versions, etc)

**Comment by RedBrogdon** [comment]
Nice catch. Do you mind trying this command to see if it does the trick for you?

`dart pub global activate grinder`

If you have the Flutter SDK installed, the cached version of dart should be available in your path, which should make that command possible. 

If it does work, I'll update the README to match.

**Comment by dym-sh** [comment]
the real problem is: grinder internally calls `pub`, so expects it to be on path

- aliasing `pub` to `dart pub` does not work ❌
- (just tried) enclosing `flutter pub $@` into a bash-script named `pub` works ✅

but i think the linked related issue with grinder itself should be resolved first

**Comment by dym-sh** [comment]
moving on..

> `webdev serve`
> webdev could not run for this project.
> Could not find a file named "pubspec.yaml" in "~/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-14.0.0".

**Comment by RedBrogdon** [comment]
Thanks for the deep dive, and for the friction notes.

Over the next couple weeks, I'm going to be revisiting the samples index as part of some related work on maintaining our repo structure, and will revisit this as I'm doing it.

**Comment by dym-sh** [comment]
im kinda surprised dart/flutter projects dont have docker-ish "setup+test+run" on new empty VMs for every release, to ensure full integrity with every other part of the final system

**Comment by ericwindmill** [comment]
Closing as the samples index is being deprecated.
