### ISSUE TITLE
[form_app] Fix sample

### ISSUE THREAD

**Issue by Ascenio** [flutter/samples#837]
For some reason the [example](https://flutter.github.io/samples/web/form_app/) doesn't show anything other than a white screen.

**Comment by RedBrogdon** [comment]
Thanks for letting us know. It looks like there's an error relating to service workers in the console.

The other web apps I checked appeared to be running without a problem, so hopefully this is limited in scope.

**Comment by zishanj** [comment]
Guys fix this main [samples](https://flutter.github.io/samples) link please

**Comment by mit-mit** [comment]
@RedBrogdon https://flutter.github.io/samples/web/navigation_and_routing/ seems to also not work

**Comment by RedBrogdon** [comment]
This has been fixed in a recent deploy. Both samples are once again hosted and working.
