### ISSUE TITLE
Sample for adding to existing iOS app SwiftUI App Life Cycle

### ISSUE THREAD

**Issue by czaku** [flutter/samples#843]
Hi,

Could someone provide or help me with creating a sample for a freshly started iOS project that does not have UIKit AppDelegate Life Cycle but SwiftUI App Life Cycle (if you generate a new project with Xcode 12 and above that is an option now).

Thanks

**Comment by domesticmouse** [comment]
@RedBrogdon who is responsible for Add to App these days?

**Comment by RedBrogdon** [comment]
Thanks for filing an issue, @czaku. Do you mind giving us a little more information about what you're looking to learn? Are you interested in building an app that combines Swift UI with Flutter, for example?

CC: @jmagman
