### ISSUE TITLE
multiple_flutters cause page lag

### ISSUE THREAD

**Issue by CoderGMLee** [flutter/samples#879]
When there are multiple engines on a page, there will be a lag on both the entry page and the exit page. I want to understand why the exit page causes the lag.
[screen shot](https://github.com/CoderGMLee/WBDemo/blob/master/Simulator%20Screen%20Shot%20-%20iPhone%2012%20Pro%20Max%20-%202021-08-20%20at%2017.00.24.png)
[cpu usage](https://github.com/CoderGMLee/WBDemo/blob/master/351629450037_.pic.jpg)

**Comment by johnpryan** [comment]
Hi @CoderGMLee, did you mean to file this to the [flutter/flutter issue tracker](https://github.com/flutter/flutter/issues)?
