### ISSUE TITLE
Update contributor's guide

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/samples#933]
Our contributor's guide is out of date and needs a refresh.

**Comment by domesticmouse** [comment]
What changes are required? I had a quick look and I don't see anything that stands out as needing updates. Halp?

**Comment by domesticmouse** [comment]
Closing out as stale. @parlough updated the contributors guide in https://github.com/flutter/samples/pull/1987 and I'm not seeing anything else that is obviously in need of modification. Please re-open if this isn't the case
