### ISSUE TITLE
`experimental/federated_plugin/federated_plugin` needs to be rebuilt for outdated Android runner

### ISSUE THREAD

**Issue by domesticmouse** [flutter/samples#963]
@AyushBherwani1998 can you provide guidance as to what is required here?

**Comment by domesticmouse** [comment]
/cc @RedBrogdon @craiglabenz 

Btw, this will become a blocker at the next stable release. It's failing the linter on beta.

**Comment by AyushBherwani1998** [comment]
Hey @domesticmouse @RedBrogdon, I hope you both are doing good.

I don't know what's the reason behind the issue here exactly, I'll try to take a look on weekend and hopefully send a RR if I'm able to figure out what exactly it's what we need.

**Comment by domesticmouse** [comment]
Thanks Ayush. My understanding is that in the Flutter beta an old Android runner is now considered a flutter warning. This PR is to turn flutter lint warnings into build failures for beta, and is thus blocking.

I'd suggest rebuilding all the runners using the current stable release. That should be enough to silence this lint warning.

**Comment by domesticmouse** [comment]
Hey @AyushBherwani1998, any chance of getting guidance on what is required to update the `federated_plugin` Android runner? This is now turning our beta CI red - https://github.com/flutter/samples/runs/4696765070?check_suite_focus=true

This will shortly become a blocker for the stable branch. I'm happy to help here, otherwise we may need to delete this sample.

FYI @RedBrogdon @craiglabenz

**Comment by AyushBherwani1998** [comment]
@domesticmouse should we try to rebuild the Android project and see if it passes?

**Comment by domesticmouse** [comment]
Is there any specific configuration of the Android runner required in those projects? I'm happy to just refresh the runners if there is no magic involved

**Comment by AyushBherwani1998** [comment]
No, there's no specific configuration required. If refreshing the runners doesn't passes the test. I'm happy to recreate the Android project on beta channel.

**Comment by domesticmouse** [comment]
I'm re-creating all of the various runners using 2.8.1. I'll send you a PR to look over soon. Thanks!
