### ISSUE TITLE
Enable mouse scrollBehavior on carousel sample

### ISSUE THREAD

**Issue by jonasjuni** [flutter/samples#964]
### Steps to reproduce
Open carousel on web:
[https://flutter.github.io/samples/web/animations/#/misc/carousel](https://flutter.github.io/samples/web/animations/#/misc/carousel)

You can't drag to change images.

would be a good ideia to add mouse as a drag device on PageView in this example?
```dart
      scrollBehavior: ScrollConfiguration.of(context).copyWith(
        dragDevices: {
          PointerDeviceKind.touch,
          PointerDeviceKind.mouse,
        },
      ),
```

**Comment by jonasjuni** [comment]
Here is my suggestion may I create a PR?
[jonasjuni/samples/blob/patch-1/animations/lib/src/misc/carousel.dart](https://github.com/jonasjuni/samples/blob/patch-1/animations/lib/src/misc/carousel.dart)

**Comment by domesticmouse** [comment]
Please create a PR and sign the CLA. Thanks!
