### ISSUE TITLE
Can react and Flutter be used for web mixed development? If so, is there a demo?

### ISSUE THREAD

**Issue by louyaming** [flutter/samples#983]
I have a Web project (single page) developed with React and now want to try to introduce Flutter for some functionality development. I wonder if there is such a scenario support?

**Comment by RedBrogdon** [comment]
We don't have a demo for this, but you could certainly compile a Flutter application and include it via an iframe in another webpage.

Sharing state or other data between React and Flutter would likely prove difficult, but I imagine that it's possible.
